/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author HP
 */
public class AppointmentForm extends javax.swing.JFrame
{
    private static final Color OK_COLOR = new Color(60, 140, 90);
    private static final Color ERR_COLOR = new Color(200, 60, 60);

    public AppointmentForm()
    {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Full screen
        setLocationRelativeTo(null);
    }

    // Getters
    public JButton getBtnBook() { return btnBook; }
    public JButton getBtnUpdate() { return btnUpdate; }
    public JButton getBtnCancelAppointment() { return btnCancelAppointment; }
    public JButton getBtnClear() { return btnClear; }
    public JComboBox<String> getCmbCustomer() { return cmbCustomer; }
    public JComboBox<String> getCmbPet() { return cmbPet; }
    public JComboBox<String> getCmbStaff() { return cmbStaff; }
    public JComboBox<String> getCmbService() { return cmbService; }
    public JTable getTable() { return tblAppointments; }
    public JTextField getTxtDate() { return txtDate; }
    public JTextField getTxtTime() { return txtTime; }
    public JTextField getTxtReason() { return txtReason; }
    public JTextField getTxtNotes() { return txtNotes; }

    // Display helpers
    public void setItems(JComboBox<String> combo, List<String> items)
    {
        combo.removeAllItems();
        items.forEach(combo::addItem);
    }

    public void setRows(List<Object[]> rows)
    {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID", "Customer", "Pet", "Staff", "Service", "Date & Time", "Status"}, 0)
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        rows.forEach(model::addRow);
        tblAppointments.setModel(model);
    }

    public void setStats(int today, int scheduled, int completed, int cancelled)
    {
        lblTodayCount.setText(String.valueOf(today));
        lblScheduledCount.setText(String.valueOf(scheduled));
        lblCompletedCount.setText(String.valueOf(completed));
        lblCancelledCount.setText(String.valueOf(cancelled));
    }

    public void showMessage(String text, boolean ok)
    {
        lblMessage.setForeground(ok ? OK_COLOR : ERR_COLOR);
        lblMessage.setText(text);
    }

    public void clearForm()
    {
        if (cmbCustomer.getItemCount() > 0) cmbCustomer.setSelectedIndex(0);
        if (cmbStaff.getItemCount() > 0) cmbStaff.setSelectedIndex(0);
        if (cmbService.getItemCount() > 0) cmbService.setSelectedIndex(0);
        txtDate.setText("");
        txtTime.setText("");
        txtReason.setText("");
        txtNotes.setText("");
        tblAppointments.clearSelection();
        lblMessage.setText("");
    }

    public void fillForm(String date, String time, String reason, String notes)
    {
        txtDate.setText(date);
        txtTime.setText(time);
        txtReason.setText(reason);
        txtNotes.setText(notes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAppointmentContent = new javax.swing.JPanel();
        pnlCardToday = new javax.swing.JPanel();
        lblTodayTitle = new javax.swing.JLabel();
        lblTodayCount = new javax.swing.JLabel();
        pnlCardScheduled = new javax.swing.JPanel();
        lblScheduledTitle = new javax.swing.JLabel();
        lblScheduledCount = new javax.swing.JLabel();
        pnlCardCompleted = new javax.swing.JPanel();
        lblCompletedCount = new javax.swing.JLabel();
        lblCompletedTitle = new javax.swing.JLabel();
        pnlCardCancelled = new javax.swing.JPanel();
        lblCancelledCount = new javax.swing.JLabel();
        lblCancelledTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlAppointmentDetails = new javax.swing.JPanel();
        lblFormSubtitle = new javax.swing.JLabel();
        lblformTitle = new javax.swing.JLabel();
        lblDateLabel = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        lblPetLabel = new javax.swing.JLabel();
        cmbPet = new javax.swing.JComboBox<>();
        lblStaffLabel = new javax.swing.JLabel();
        cmbStaff = new javax.swing.JComboBox<>();
        lblServiceLabel = new javax.swing.JLabel();
        cmbService = new javax.swing.JComboBox<>();
        lblCustomerLabel = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblTimeTable = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        lblReasonLabel = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        txtNotes = new javax.swing.JTextField();
        lblNotes = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancelAppointment = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblRecentsAppointments = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setSize(new java.awt.Dimension(1500, 900));

        pnlAppointmentContent.setBackground(new java.awt.Color(250, 246, 240));
        pnlAppointmentContent.setMinimumSize(new java.awt.Dimension(1200, 900));
        pnlAppointmentContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCardToday.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardToday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardToday.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTodayTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTodayTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblTodayTitle.setText("TODAY");
        pnlCardToday.add(lblTodayTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblTodayCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTodayCount.setForeground(new java.awt.Color(74, 91, 106));
        lblTodayCount.setText("0");
        pnlCardToday.add(lblTodayCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlAppointmentContent.add(pnlCardToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 90));

        pnlCardScheduled.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardScheduled.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardScheduled.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScheduledTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblScheduledTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblScheduledTitle.setText("SHEDULED");
        pnlCardScheduled.add(lblScheduledTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblScheduledCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblScheduledCount.setForeground(new java.awt.Color(74, 91, 106));
        lblScheduledCount.setText("0");
        pnlCardScheduled.add(lblScheduledCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlAppointmentContent.add(pnlCardScheduled, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 280, 90));

        pnlCardCompleted.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardCompleted.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardCompleted.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCompletedCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblCompletedCount.setForeground(new java.awt.Color(74, 91, 106));
        lblCompletedCount.setText("0");
        pnlCardCompleted.add(lblCompletedCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblCompletedTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCompletedTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblCompletedTitle.setText("COMPLETED");
        pnlCardCompleted.add(lblCompletedTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlAppointmentContent.add(pnlCardCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 280, 90));

        pnlCardCancelled.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardCancelled.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardCancelled.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCancelledCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblCancelledCount.setForeground(new java.awt.Color(74, 91, 106));
        lblCancelledCount.setText("0");
        pnlCardCancelled.add(lblCancelledCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblCancelledTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCancelledTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblCancelledTitle.setText("CANCELLED");
        pnlCardCancelled.add(lblCancelledTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlAppointmentContent.add(pnlCardCancelled, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 280, 90));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblTitle.setText("Appointments");
        pnlAppointmentContent.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 35));

        lblSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblSubtitle.setText("Book and manage appointments");
        pnlAppointmentContent.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 20));

        pnlAppointmentDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlAppointmentDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlAppointmentDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblFormSubtitle.setText("Register and manage appointment bookings");
        pnlAppointmentDetails.add(lblFormSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, 500, 20));

        lblformTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblformTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblformTitle.setText("APPOINTMENT BOOKING");
        pnlAppointmentDetails.add(lblformTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 25));

        lblDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDateLabel.setForeground(new java.awt.Color(113, 128, 140));
        lblDateLabel.setText("DATE (YYYY-MM-DD)");
        pnlAppointmentDetails.add(lblDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 366, 18));

        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAppointmentDetails.add(cmbCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 32));

        lblPetLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPetLabel.setForeground(new java.awt.Color(113, 128, 140));
        lblPetLabel.setText("PET");
        pnlAppointmentDetails.add(lblPetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 270, 18));

        cmbPet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAppointmentDetails.add(cmbPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 270, 32));

        lblStaffLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStaffLabel.setForeground(new java.awt.Color(113, 128, 140));
        lblStaffLabel.setText("STAFF");
        pnlAppointmentDetails.add(lblStaffLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 270, 18));

        cmbStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAppointmentDetails.add(cmbStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 270, 32));

        lblServiceLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblServiceLabel.setForeground(new java.awt.Color(113, 128, 140));
        lblServiceLabel.setText("SERVICE");
        pnlAppointmentDetails.add(lblServiceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 270, 18));

        cmbService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAppointmentDetails.add(cmbService, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 270, 32));

        lblCustomerLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCustomerLabel.setForeground(new java.awt.Color(113, 128, 140));
        lblCustomerLabel.setText("CUSTOMER");
        pnlAppointmentDetails.add(lblCustomerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, 18));
        pnlAppointmentDetails.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 366, 32));

        lblTimeTable.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTimeTable.setForeground(new java.awt.Color(113, 128, 140));
        lblTimeTable.setText("TIME (HH:MM)");
        pnlAppointmentDetails.add(lblTimeTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 160, 366, 18));
        pnlAppointmentDetails.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 180, 366, 32));

        lblReasonLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblReasonLabel.setForeground(new java.awt.Color(113, 128, 140));
        lblReasonLabel.setText("REASON");
        pnlAppointmentDetails.add(lblReasonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 160, 366, 18));
        pnlAppointmentDetails.add(txtReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 180, 366, 32));
        pnlAppointmentDetails.add(txtNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 1140, 70));

        lblNotes.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblNotes.setForeground(new java.awt.Color(113, 128, 140));
        lblNotes.setText("NOTES");
        pnlAppointmentDetails.add(lblNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1140, 18));

        lblMessage.setForeground(java.awt.Color.red);
        pnlAppointmentDetails.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 600, 20));

        btnBook.setBackground(new java.awt.Color(157, 201, 163));
        btnBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBook.setForeground(new java.awt.Color(74, 91, 106));
        btnBook.setText("Book Appointment");
        pnlAppointmentDetails.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 355, 270, 45));

        btnUpdate.setBackground(new java.awt.Color(190, 210, 230));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(74, 91, 106));
        btnUpdate.setText("Update Status");
        pnlAppointmentDetails.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 355, 270, 45));

        btnCancelAppointment.setBackground(new java.awt.Color(220, 170, 170));
        btnCancelAppointment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelAppointment.setForeground(new java.awt.Color(120, 40, 40));
        btnCancelAppointment.setText("Cancel");
        pnlAppointmentDetails.add(btnCancelAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 355, 270, 45));

        btnClear.setBackground(new java.awt.Color(235, 235, 230));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(74, 91, 106));
        btnClear.setText("Clear");
        pnlAppointmentDetails.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 355, 270, 45));

        pnlAppointmentContent.add(pnlAppointmentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1180, 420));

        lblRecentsAppointments.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblRecentsAppointments.setForeground(new java.awt.Color(113, 128, 140));
        lblRecentsAppointments.setText("RECENT APPOINTMENTS");
        pnlAppointmentContent.add(lblRecentsAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 400, 25));

        tblAppointments.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Customer", "Pet", "Staff", "Service", "Date & Time", "Status"
            }
        ));
        tblAppointments.setRowHeight(28);
        jScrollPane1.setViewportView(tblAppointments);

        pnlAppointmentContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 658, 1180, 250));

        getContentPane().add(pnlAppointmentContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancelAppointment;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbPet;
    private javax.swing.JComboBox<String> cmbService;
    private javax.swing.JComboBox<String> cmbStaff;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCancelledCount;
    private javax.swing.JLabel lblCancelledTitle;
    private javax.swing.JLabel lblCompletedCount;
    private javax.swing.JLabel lblCompletedTitle;
    private javax.swing.JLabel lblCustomerLabel;
    private javax.swing.JLabel lblDateLabel;
    private javax.swing.JLabel lblFormSubtitle;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblPetLabel;
    private javax.swing.JLabel lblReasonLabel;
    private javax.swing.JLabel lblRecentsAppointments;
    private javax.swing.JLabel lblScheduledCount;
    private javax.swing.JLabel lblScheduledTitle;
    private javax.swing.JLabel lblServiceLabel;
    private javax.swing.JLabel lblStaffLabel;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTimeTable;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTodayCount;
    private javax.swing.JLabel lblTodayTitle;
    private javax.swing.JLabel lblformTitle;
    private javax.swing.JPanel pnlAppointmentContent;
    private javax.swing.JPanel pnlAppointmentDetails;
    private javax.swing.JPanel pnlCardCancelled;
    private javax.swing.JPanel pnlCardCompleted;
    private javax.swing.JPanel pnlCardScheduled;
    private javax.swing.JPanel pnlCardToday;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtReason;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
