/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import service.CustomerService;
import model.Customer;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class CustomerForm extends javax.swing.JFrame {
    
    private final CustomerService customerService = new CustomerService();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerForm.class.getName());

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() 
    {
        initComponents();
        setResizable(false);
        sidebarPanel1.setActiveItem("CUSTOMERS");
        sidebarPanel1.setNavigationListener(this::handleSidebarNavigation);
        
        // LOAD CUSTOMERS WHEN FORM OPENS
        loadCustomers();
    }
    private void handleSidebarNavigation(String screen) {
       switch (screen) {
           case "PET PATIENTS" -> {
               new PetForm().setVisible(true);
               this.dispose();
           }
           default -> {
               // not built yet
           }
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlCustomerContent = new javax.swing.JPanel();
        pnlCustomerDetails = new javax.swing.JPanel();
        lblCustomerDetailsTitle = new javax.swing.JLabel();
        lblCustomerDetailsSubtitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        pnlTotalCustomers = new javax.swing.JPanel();
        lblTotalCustomersTitle = new javax.swing.JLabel();
        lblTotalCustomersCount = new javax.swing.JLabel();
        lblTotalCustomersSubtitle = new javax.swing.JLabel();
        lblTotalCustomersIcon = new javax.swing.JLabel();
        pnlActiveCustomers = new javax.swing.JPanel();
        lblActiveCustomersTitle = new javax.swing.JLabel();
        lblActiveCustomersCount = new javax.swing.JLabel();
        lblActiveCustomersSubtitle = new javax.swing.JLabel();
        lblActiveCustomersIcon = new javax.swing.JLabel();
        pnlInactiveCustomers = new javax.swing.JPanel();
        lblInactiveCustomersTitle = new javax.swing.JLabel();
        lblInactiveCustomersCount = new javax.swing.JLabel();
        lblInactiveCustomersSubtitle = new javax.swing.JLabel();
        lblInactiveCustomersIcon = new javax.swing.JLabel();
        btnNewCustomer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblBreadcrumb = new javax.swing.JLabel();
        lblClinicName = new javax.swing.JLabel();
        lblStatusDot = new javax.swing.JLabel();
        lblStatusText = new javax.swing.JLabel();
        lblCustomerTitle = new javax.swing.JLabel();
        lblCustomerSubtitle = new javax.swing.JLabel();
        sidebarPanel1 = new view.SidebarPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 246, 242));
        setBounds(new java.awt.Rectangle(0, 0, 1400, 900));
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 900));

        jPanel1.setBackground(new java.awt.Color(248, 246, 242));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlCustomerContent.setBackground(new java.awt.Color(248, 246, 242));
        pnlCustomerContent.setMinimumSize(new java.awt.Dimension(1150, 900));
        pnlCustomerContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCustomerDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlCustomerDetails.setToolTipText("");
        pnlCustomerDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomerDetailsTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCustomerDetailsTitle.setForeground(new java.awt.Color(48, 70, 90));
        lblCustomerDetailsTitle.setText("CUSTOMER DETAILS");
        pnlCustomerDetails.add(lblCustomerDetailsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 300, 28));

        lblCustomerDetailsSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblCustomerDetailsSubtitle.setForeground(new java.awt.Color(113, 128, 140));
        lblCustomerDetailsSubtitle.setText("Register and manage pet owner information");
        pnlCustomerDetails.add(lblCustomerDetailsSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 400, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(113, 128, 140));
        jLabel1.setText("FULL NAME");
        pnlCustomerDetails.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 280, 18));

        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(48, 70, 90));
        txtFullName.setToolTipText("Enter full name, e.g. John Silva");
        txtFullName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        txtFullName.addActionListener(this::txtFullNameActionPerformed);
        pnlCustomerDetails.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 280, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(113, 128, 140));
        jLabel2.setText("PHONE");
        pnlCustomerDetails.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 280, 18));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(48, 70, 90));
        txtPhone.setToolTipText("Enter Sri Lankan mobile number, e.g. 0771234567");
        txtPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        txtPhone.addActionListener(this::txtPhoneActionPerformed);
        pnlCustomerDetails.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 280, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(113, 128, 140));
        jLabel3.setText("EMAIL");
        pnlCustomerDetails.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 280, 18));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(48, 70, 90));
        txtEmail.setToolTipText("Enter valid email, e.g. john@gmail.com");
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        txtEmail.addActionListener(this::txtEmailActionPerformed);
        pnlCustomerDetails.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 280, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(113, 128, 140));
        jLabel4.setText("ADDRESS");
        pnlCustomerDetails.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 270, 18));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(48, 70, 90));
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        txtAddress.addActionListener(this::txtAddressActionPerformed);
        pnlCustomerDetails.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 270, 45));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(113, 128, 140));
        jLabel5.setText("CUSTOMER ID");
        pnlCustomerDetails.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 270, 18));

        txtCustomerId.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCustomerId.setForeground(new java.awt.Color(48, 70, 90));
        txtCustomerId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        txtCustomerId.addActionListener(this::txtCustomerIdActionPerformed);
        pnlCustomerDetails.add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 270, 32));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(113, 128, 140));
        jLabel6.setText("STATUS");
        pnlCustomerDetails.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 280, 18));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", " " }));
        cmbStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        pnlCustomerDetails.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 280, 32));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(80, 80, 80));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        btnClear.addActionListener(this::btnClearActionPerformed);
        pnlCustomerDetails.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 240, 42));

        btnAdd1.setBackground(new java.awt.Color(62, 107, 82));
        btnAdd1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd1.setText("Add Customer");
        btnAdd1.addActionListener(this::btnAdd1ActionPerformed);
        pnlCustomerDetails.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, 42));

        btnUpdate1.setBackground(new java.awt.Color(232, 236, 238));
        btnUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(80, 80, 80));
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(this::btnUpdate1ActionPerformed);
        pnlCustomerDetails.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 200, 42));

        btnDelete1.setBackground(new java.awt.Color(247, 220, 224));
        btnDelete1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(122, 46, 54));
        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(this::btnDelete1ActionPerformed);
        pnlCustomerDetails.add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 200, 42));

        pnlCustomerContent.add(pnlCustomerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 280, 1185, 320));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Full Name", "Phone", "Email", "Address", "Status"
            }
        ));
        tblCustomers.setRowHeight(28);
        tblCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomers);

        pnlCustomerContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 620, 1185, 260));

        pnlTotalCustomers.setBackground(new java.awt.Color(255, 255, 255));
        pnlTotalCustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalCustomersTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalCustomersTitle.setForeground(new java.awt.Color(113, 128, 140));
        lblTotalCustomersTitle.setText("TOTAL CUSTOMERS");
        pnlTotalCustomers.add(lblTotalCustomersTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, 300, 20));

        lblTotalCustomersCount.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTotalCustomersCount.setForeground(new java.awt.Color(48, 70, 90));
        lblTotalCustomersCount.setText("0");
        pnlTotalCustomers.add(lblTotalCustomersCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 150, 45));

        lblTotalCustomersSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTotalCustomersSubtitle.setForeground(new java.awt.Color(150, 160, 168));
        lblTotalCustomersSubtitle.setText("All registered owners");
        pnlTotalCustomers.add(lblTotalCustomersSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 88, 300, 18));

        lblTotalCustomersIcon.setBackground(new java.awt.Color(240, 244, 240));
        lblTotalCustomersIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalCustomersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalCustomersIcon.setText("T");
        lblTotalCustomersIcon.setOpaque(true);
        pnlTotalCustomers.add(lblTotalCustomersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 45, 45));

        pnlCustomerContent.add(pnlTotalCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 145, 381, 110));
        pnlTotalCustomers.getAccessibleContext().setAccessibleDescription("");

        pnlActiveCustomers.setBackground(new java.awt.Color(255, 255, 255));
        pnlActiveCustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblActiveCustomersTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblActiveCustomersTitle.setForeground(new java.awt.Color(113, 128, 140));
        lblActiveCustomersTitle.setText("ACTIVE");
        pnlActiveCustomers.add(lblActiveCustomersTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, 300, 20));

        lblActiveCustomersCount.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblActiveCustomersCount.setForeground(new java.awt.Color(48, 70, 90));
        lblActiveCustomersCount.setText("0");
        pnlActiveCustomers.add(lblActiveCustomersCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 150, 45));

        lblActiveCustomersSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblActiveCustomersSubtitle.setForeground(new java.awt.Color(150, 160, 168));
        lblActiveCustomersSubtitle.setText("Currently active");
        pnlActiveCustomers.add(lblActiveCustomersSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 88, 300, 18));

        lblActiveCustomersIcon.setBackground(new java.awt.Color(230, 245, 235));
        lblActiveCustomersIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblActiveCustomersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActiveCustomersIcon.setText("A");
        lblActiveCustomersIcon.setOpaque(true);
        pnlActiveCustomers.add(lblActiveCustomersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 45, 45));

        pnlCustomerContent.add(pnlActiveCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 145, 381, 110));

        pnlInactiveCustomers.setBackground(new java.awt.Color(255, 255, 255));
        pnlInactiveCustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInactiveCustomersTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInactiveCustomersTitle.setForeground(new java.awt.Color(113, 128, 140));
        lblInactiveCustomersTitle.setText("INACTIVE");
        pnlInactiveCustomers.add(lblInactiveCustomersTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, 300, 20));

        lblInactiveCustomersCount.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblInactiveCustomersCount.setForeground(new java.awt.Color(48, 70, 90));
        lblInactiveCustomersCount.setText("0");
        pnlInactiveCustomers.add(lblInactiveCustomersCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 150, 45));

        lblInactiveCustomersSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblInactiveCustomersSubtitle.setForeground(new java.awt.Color(150, 160, 168));
        lblInactiveCustomersSubtitle.setText("Currently inactive");
        pnlInactiveCustomers.add(lblInactiveCustomersSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 88, 300, 18));

        lblInactiveCustomersIcon.setBackground(new java.awt.Color(250, 235, 235));
        lblInactiveCustomersIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInactiveCustomersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInactiveCustomersIcon.setText("I");
        lblInactiveCustomersIcon.setOpaque(true);
        pnlInactiveCustomers.add(lblInactiveCustomersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 45, 45));

        pnlCustomerContent.add(pnlInactiveCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 145, 381, 110));

        btnNewCustomer.setBackground(new java.awt.Color(60, 90, 100));
        btnNewCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNewCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnNewCustomer.setText("+ NEW CUSTOMER");
        btnNewCustomer.setBorder(null);
        btnNewCustomer.addActionListener(this::btnNewCustomerActionPerformed);
        pnlCustomerContent.add(btnNewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, 210, 42));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBreadcrumb.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblBreadcrumb.setForeground(new java.awt.Color(200, 150, 60));
        lblBreadcrumb.setText("CLINIC / CUSTOMER REGISTRY");
        jPanel2.add(lblBreadcrumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, -1));

        lblClinicName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClinicName.setForeground(new java.awt.Color(48, 70, 90));
        lblClinicName.setText("PawCare 360 Veterinary Centre");
        jPanel2.add(lblClinicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 35, 400, 22));

        lblStatusDot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStatusDot.setForeground(new java.awt.Color(76, 175, 80));
        lblStatusDot.setText(".");
        jPanel2.add(lblStatusDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 30, 30));

        lblStatusText.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblStatusText.setForeground(new java.awt.Color(76, 175, 80));
        lblStatusText.setText("CLINIC SYSTEM ONLINE");
        jPanel2.add(lblStatusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1115, 25, -1, -1));

        pnlCustomerContent.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 70));

        lblCustomerTitle.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblCustomerTitle.setForeground(new java.awt.Color(48, 70, 90));
        lblCustomerTitle.setText("Customers");
        pnlCustomerContent.add(lblCustomerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, 400, 40));

        lblCustomerSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblCustomerSubtitle.setForeground(new java.awt.Color(113, 128, 140));
        lblCustomerSubtitle.setText("Register and manage every pet owner in our care.");
        pnlCustomerContent.add(lblCustomerSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, -1, -1));

        jPanel1.add(pnlCustomerContent, java.awt.BorderLayout.CENTER);
        jPanel1.add(sidebarPanel1, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 1506, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIdActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       clearFields(); 
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // VALIDATE INPUT 
        if (!validateCustomerInput()) 
        {
            return;
        }
        try 
        {
            int customerId = Integer.parseInt(
                    txtCustomerId.getText().trim()
            );

            String fullName = txtFullName.getText().trim();
            String phone = txtPhone.getText().trim();
            String email = txtEmail.getText().trim();
            String address = txtAddress.getText().trim();

            Customer customer = new Customer();

            customer.setCustomerId(customerId);
            customer.setFullName(fullName);
            customer.setPhone(phone);
            customer.setEmail(email);
            customer.setAddress(address);
            customer.setStatus(cmbStatus.getSelectedItem().toString());

            boolean success = customerService.updateCustomer(customer);

            if (success) 
            {
                JOptionPane.showMessageDialog(
                        this,
                        "Customer updated successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();
                loadCustomers();
            } 
            else 
            {
                JOptionPane.showMessageDialog(
                        this,
                        "Customer update failed.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
        catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a valid customer.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
        } 
        catch (IllegalArgumentException e) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "An unexpected error occurred.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // CHECK WHETHER A CUSTOMER IS SELECTED
        if (txtCustomerId.getText().trim().isEmpty()) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a customer to delete.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // CONFIRM BEFORE DELETING
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this customer?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) 
        {
            return;
        }
        
        try 
        {
            int customerId = Integer.parseInt(
                    txtCustomerId.getText().trim()
            );
            
            boolean success = customerService.deleteCustomer(customerId);

            if (success) 
            {
                JOptionPane.showMessageDialog(
                        this,
                        "Customer deleted successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();
                loadCustomers();
            } 
            else 
            {
                JOptionPane.showMessageDialog(
                        this,
                        "Customer could not be deleted.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } 
        catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Invalid customer ID.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "An unexpected error occurred.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        //VALIDATE INPUT
        if (!validateCustomerInput()) 
        {
            return;
        }
        try 
        {
            String fullName = txtFullName.getText().trim();
            String phone = txtPhone.getText().trim();
            String email = txtEmail.getText().trim();
            String address = txtAddress.getText().trim();

            Customer customer = new Customer();

            customer.setFullName(fullName);
            customer.setPhone(phone);
            customer.setEmail(email);
            customer.setAddress(address);
            customer.setStatus(cmbStatus.getSelectedItem().toString());

            boolean success = customerService.addCustomer(customer);

            if (success) 
            {
                JOptionPane.showMessageDialog(
                        this,
                        "Customer added successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );

                clearFields();
                loadCustomers();

            } 
            else 
            {
                JOptionPane.showMessageDialog(
                        this,
                        "Failed to add customer.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        } 
        catch (IllegalArgumentException e) 
        {
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
            );

        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(
                this,
                "An unexpected error occurred.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void tblCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomersMouseClicked
        // GET SELECTED CUSTOMER FROM TABLE
        int selectedRow = tblCustomers.getSelectedRow();

        if (selectedRow >= 0) 
        {
            txtCustomerId.setText(
                    tblCustomers.getValueAt(selectedRow, 0).toString()
            );

            txtFullName.setText(
                    tblCustomers.getValueAt(selectedRow, 1).toString()
            );

            txtPhone.setText(
                    tblCustomers.getValueAt(selectedRow, 2).toString()
            );

            txtEmail.setText(
                    tblCustomers.getValueAt(selectedRow, 3).toString()
            );

            txtAddress.setText(
                    tblCustomers.getValueAt(selectedRow, 4).toString()
            );
            
            cmbStatus.setSelectedItem(
                    tblCustomers.getValueAt(selectedRow, 5).toString()
            );
        }
        
    }//GEN-LAST:event_tblCustomersMouseClicked

    private void btnNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCustomerActionPerformed
        clearFields();
        txtFullName.requestFocus();
    }//GEN-LAST:event_btnNewCustomerActionPerformed
    //Clear text fields
    private void clearFields() 
    {

        txtCustomerId.setText("");
        txtFullName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtAddress.setText("");

        cmbStatus.setSelectedItem("Active");
    }
    
    private void loadCustomers() 
    {
        try 
        {
            java.util.List<Customer> customers =
                    customerService.getAllCustomers();

            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) tblCustomers.getModel();

            model.setRowCount(0);

            for (Customer customer : customers) 
            {
                model.addRow(new Object[]{
                    customer.getCustomerId(),
                    customer.getFullName(),
                    customer.getPhone(),
                    customer.getEmail(),
                    customer.getAddress(),
                    customer.getStatus()
                });
            }

            // COUNT ACTIVE / INACTIVE CUSTOMERS FOR STAT CARDS
            int activeCount = 0;
            int inactiveCount = 0;

            for (Customer c : customers) 
            {
                if ("Active".equalsIgnoreCase(c.getStatus())) 
                {
                    activeCount++;
                } 
                else 
                {
                    inactiveCount++;
                }
            }

            lblTotalCustomersCount.setText(String.valueOf(customers.size()));
            lblActiveCustomersCount.setText(String.valueOf(activeCount));
            lblInactiveCustomersCount.setText(String.valueOf(inactiveCount));

        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Failed to load customers.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    // VALIDATE CUSTOMER INPUT
    private boolean validateCustomerInput() 
    {

        String fullName = txtFullName.getText().trim();
        String phone = txtPhone.getText().trim();
        String email = txtEmail.getText().trim();
        String address = txtAddress.getText().trim();

        // Full Name
        if (fullName.isEmpty()) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Please enter the customer's full name.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
            txtFullName.requestFocus();
            return false;
        }
        if (!fullName.matches("[a-zA-Z .']+")) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Full name can contain only letters, spaces, dots and apostrophes.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
            txtFullName.requestFocus();
            return false;
        }

        // Phone
        if (phone.isEmpty()) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Please enter the customer's phone number.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
            txtPhone.requestFocus();
            return false;
        }
        if (!phone.matches("^(07\\d{8}|\\+947\\d{8})$")) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Please enter a valid Sri Lankan mobile number.\nExample: 0771234567",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
            txtPhone.requestFocus();
            return false;
        }

        // Email
        if (email.isEmpty()) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Please enter the customer's email address.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
            txtEmail.requestFocus();
            return false;
        }
        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Please enter a valid email address.\nExample: john@gmail.com",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
            txtEmail.requestFocus();
            return false;
        }

        // Address
        if (address.isEmpty()) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Please enter the customer's address.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
            txtAddress.requestFocus();
            return false;
        }
        if (address.length() < 5) 
        {
            JOptionPane.showMessageDialog(
                    this,
                    "Please enter a complete address.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );
            txtAddress.requestFocus();
            return false;
        }
        
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerForm().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnNewCustomer;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActiveCustomersCount;
    private javax.swing.JLabel lblActiveCustomersIcon;
    private javax.swing.JLabel lblActiveCustomersSubtitle;
    private javax.swing.JLabel lblActiveCustomersTitle;
    private javax.swing.JLabel lblBreadcrumb;
    private javax.swing.JLabel lblClinicName;
    private javax.swing.JLabel lblCustomerDetailsSubtitle;
    private javax.swing.JLabel lblCustomerDetailsTitle;
    private javax.swing.JLabel lblCustomerSubtitle;
    private javax.swing.JLabel lblCustomerTitle;
    private javax.swing.JLabel lblInactiveCustomersCount;
    private javax.swing.JLabel lblInactiveCustomersIcon;
    private javax.swing.JLabel lblInactiveCustomersSubtitle;
    private javax.swing.JLabel lblInactiveCustomersTitle;
    private javax.swing.JLabel lblStatusDot;
    private javax.swing.JLabel lblStatusText;
    private javax.swing.JLabel lblTotalCustomersCount;
    private javax.swing.JLabel lblTotalCustomersIcon;
    private javax.swing.JLabel lblTotalCustomersSubtitle;
    private javax.swing.JLabel lblTotalCustomersTitle;
    private javax.swing.JPanel pnlActiveCustomers;
    private javax.swing.JPanel pnlCustomerContent;
    private javax.swing.JPanel pnlCustomerDetails;
    private javax.swing.JPanel pnlInactiveCustomers;
    private javax.swing.JPanel pnlTotalCustomers;
    private view.SidebarPanel sidebarPanel1;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
