package view;

import javax.swing.table.DefaultTableModel;

/**
 * Passive customer view.
 */
public class CustomerForm extends javax.swing.JFrame {

    public CustomerForm()
    {
        initComponents();
        setResizable(true);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Full screen
        setLocationRelativeTo(null);
        readOnlyTable();
    }

    // Cells not editable
    private void readOnlyTable()
    {
        DefaultTableModel old = (DefaultTableModel) tblCustomers.getModel();
        String[] cols = new String[old.getColumnCount()];
        for (int i = 0; i < cols.length; i++)
        {
            cols[i] = old.getColumnName(i);
        }
        tblCustomers.setModel(new DefaultTableModel(new Object[0][], cols)
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlCustomerContent = new javax.swing.JPanel();
        pnlCustomerDetails = new javax.swing.JPanel();
        lblCustomerDetailsTitle = new javax.swing.JLabel();
        lblCustomerDetailsSubtitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        pnlTotalCustomers = new javax.swing.JPanel();
        lblTotalCustomersTitle = new javax.swing.JLabel();
        lblTotalCustomersCount = new javax.swing.JLabel();
        lblTotalCustomersSubtitle = new javax.swing.JLabel();
        lblTotalCustomersIcon = new javax.swing.JLabel();
        pnlActiveCustomers = new javax.swing.JPanel();
        lblActiveCustomersTitle = new javax.swing.JLabel();
        lblActiveCustomersCount = new javax.swing.JLabel();
        lblActiveCustomersSubtitle = new javax.swing.JLabel();
        lblActiveCustomersIcon = new javax.swing.JLabel();
        pnlInactiveCustomers = new javax.swing.JPanel();
        lblInactiveCustomersTitle = new javax.swing.JLabel();
        lblInactiveCustomersCount = new javax.swing.JLabel();
        lblInactiveCustomersSubtitle = new javax.swing.JLabel();
        lblInactiveCustomersIcon = new javax.swing.JLabel();
        btnNewCustomer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblBreadcrumb = new javax.swing.JLabel();
        lblClinicName = new javax.swing.JLabel();
        lblStatusDot = new javax.swing.JLabel();
        lblStatusText = new javax.swing.JLabel();
        lblCustomerTitle = new javax.swing.JLabel();
        lblCustomerSubtitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 246, 242));
        setBounds(new java.awt.Rectangle(0, 0, 1400, 900));
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 900));

        jPanel1.setBackground(new java.awt.Color(248, 246, 242));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlCustomerContent.setBackground(new java.awt.Color(248, 246, 242));
        pnlCustomerContent.setMinimumSize(new java.awt.Dimension(1150, 900));
        pnlCustomerContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCustomerDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlCustomerDetails.setToolTipText("");
        pnlCustomerDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomerDetailsTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCustomerDetailsTitle.setForeground(new java.awt.Color(48, 70, 90));
        lblCustomerDetailsTitle.setText("CUSTOMER DETAILS");
        pnlCustomerDetails.add(lblCustomerDetailsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 300, 28));

        lblCustomerDetailsSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblCustomerDetailsSubtitle.setForeground(new java.awt.Color(113, 128, 140));
        lblCustomerDetailsSubtitle.setText("Register and manage pet owner information");
        pnlCustomerDetails.add(lblCustomerDetailsSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 400, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(113, 128, 140));
        jLabel1.setText("FULL NAME");
        pnlCustomerDetails.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 280, 18));

        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(48, 70, 90));
        txtFullName.setToolTipText("Enter full name, e.g. John Silva");
        txtFullName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        pnlCustomerDetails.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 280, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(113, 128, 140));
        jLabel2.setText("PHONE");
        pnlCustomerDetails.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 280, 18));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(48, 70, 90));
        txtPhone.setToolTipText("Enter Sri Lankan mobile number, e.g. 0771234567");
        txtPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        pnlCustomerDetails.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 280, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(113, 128, 140));
        jLabel3.setText("EMAIL");
        pnlCustomerDetails.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 280, 18));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(48, 70, 90));
        txtEmail.setToolTipText("Enter valid email, e.g. john@gmail.com");
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        pnlCustomerDetails.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 590, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(113, 128, 140));
        jLabel4.setText("ADDRESS");
        pnlCustomerDetails.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 270, 18));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(48, 70, 90));
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        pnlCustomerDetails.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 570, 45));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(113, 128, 140));
        jLabel5.setText("CUSTOMER ID");
        pnlCustomerDetails.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 280, 18));

        txtCustomerId.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtCustomerId.setForeground(new java.awt.Color(48, 70, 90));
        txtCustomerId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        pnlCustomerDetails.add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 280, 32));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(113, 128, 140));
        jLabel6.setText("STATUS");
        pnlCustomerDetails.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 250, 18));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", " " }));
        cmbStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        pnlCustomerDetails.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 260, 32));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(80, 80, 80));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 214, 218)));
        pnlCustomerDetails.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, 240, 42));

        btnAdd1.setBackground(new java.awt.Color(62, 107, 82));
        btnAdd1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd1.setText("Add Customer");
        pnlCustomerDetails.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 200, 42));

        btnUpdate1.setBackground(new java.awt.Color(232, 236, 238));
        btnUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(80, 80, 80));
        btnUpdate1.setText("Update");
        pnlCustomerDetails.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 200, 42));

        btnDelete1.setBackground(new java.awt.Color(247, 220, 224));
        btnDelete1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(122, 46, 54));
        btnDelete1.setText("Delete");
        pnlCustomerDetails.add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 200, 42));

        pnlCustomerContent.add(pnlCustomerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 280, 1240, 320));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Full Name", "Phone", "Email", "Address", "Status"
            }
        ));
        tblCustomers.setRowHeight(28);
        jScrollPane1.setViewportView(tblCustomers);

        pnlCustomerContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 620, 1240, 260));

        pnlTotalCustomers.setBackground(new java.awt.Color(255, 255, 255));
        pnlTotalCustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalCustomersTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalCustomersTitle.setForeground(new java.awt.Color(113, 128, 140));
        lblTotalCustomersTitle.setText("TOTAL CUSTOMERS");
        pnlTotalCustomers.add(lblTotalCustomersTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, 300, 20));

        lblTotalCustomersCount.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTotalCustomersCount.setForeground(new java.awt.Color(48, 70, 90));
        lblTotalCustomersCount.setText("0");
        pnlTotalCustomers.add(lblTotalCustomersCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 150, 45));

        lblTotalCustomersSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTotalCustomersSubtitle.setForeground(new java.awt.Color(150, 160, 168));
        lblTotalCustomersSubtitle.setText("All registered owners");
        pnlTotalCustomers.add(lblTotalCustomersSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 88, 300, 18));

        lblTotalCustomersIcon.setBackground(new java.awt.Color(240, 244, 240));
        lblTotalCustomersIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalCustomersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalCustomersIcon.setText("T");
        lblTotalCustomersIcon.setOpaque(true);
        pnlTotalCustomers.add(lblTotalCustomersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 45, 45));

        pnlCustomerContent.add(pnlTotalCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 145, 381, 110));
        pnlTotalCustomers.getAccessibleContext().setAccessibleDescription("");

        pnlActiveCustomers.setBackground(new java.awt.Color(255, 255, 255));
        pnlActiveCustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblActiveCustomersTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblActiveCustomersTitle.setForeground(new java.awt.Color(113, 128, 140));
        lblActiveCustomersTitle.setText("ACTIVE");
        pnlActiveCustomers.add(lblActiveCustomersTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, 300, 20));

        lblActiveCustomersCount.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblActiveCustomersCount.setForeground(new java.awt.Color(48, 70, 90));
        lblActiveCustomersCount.setText("0");
        pnlActiveCustomers.add(lblActiveCustomersCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 150, 45));

        lblActiveCustomersSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblActiveCustomersSubtitle.setForeground(new java.awt.Color(150, 160, 168));
        lblActiveCustomersSubtitle.setText("Currently active");
        pnlActiveCustomers.add(lblActiveCustomersSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 88, 300, 18));

        lblActiveCustomersIcon.setBackground(new java.awt.Color(230, 245, 235));
        lblActiveCustomersIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblActiveCustomersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActiveCustomersIcon.setText("A");
        lblActiveCustomersIcon.setOpaque(true);
        pnlActiveCustomers.add(lblActiveCustomersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 45, 45));

        pnlCustomerContent.add(pnlActiveCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 145, 381, 110));

        pnlInactiveCustomers.setBackground(new java.awt.Color(255, 255, 255));
        pnlInactiveCustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInactiveCustomersTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInactiveCustomersTitle.setForeground(new java.awt.Color(113, 128, 140));
        lblInactiveCustomersTitle.setText("INACTIVE");
        pnlInactiveCustomers.add(lblInactiveCustomersTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, 300, 20));

        lblInactiveCustomersCount.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblInactiveCustomersCount.setForeground(new java.awt.Color(48, 70, 90));
        lblInactiveCustomersCount.setText("0");
        pnlInactiveCustomers.add(lblInactiveCustomersCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 150, 45));

        lblInactiveCustomersSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblInactiveCustomersSubtitle.setForeground(new java.awt.Color(150, 160, 168));
        lblInactiveCustomersSubtitle.setText("Currently inactive");
        pnlInactiveCustomers.add(lblInactiveCustomersSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 88, 300, 18));

        lblInactiveCustomersIcon.setBackground(new java.awt.Color(250, 235, 235));
        lblInactiveCustomersIcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInactiveCustomersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInactiveCustomersIcon.setText("I");
        lblInactiveCustomersIcon.setOpaque(true);
        pnlInactiveCustomers.add(lblInactiveCustomersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 45, 45));

        pnlCustomerContent.add(pnlInactiveCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 145, 381, 110));

        btnNewCustomer.setBackground(new java.awt.Color(60, 90, 100));
        btnNewCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNewCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnNewCustomer.setText("+ NEW CUSTOMER");
        btnNewCustomer.setBorder(null);
        pnlCustomerContent.add(btnNewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 90, 210, 42));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBreadcrumb.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblBreadcrumb.setForeground(new java.awt.Color(200, 150, 60));
        lblBreadcrumb.setText("CLINIC / CUSTOMER REGISTRY");
        jPanel2.add(lblBreadcrumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, -1));

        lblClinicName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClinicName.setForeground(new java.awt.Color(48, 70, 90));
        lblClinicName.setText("PawCare 360 Veterinary Centre");
        jPanel2.add(lblClinicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 35, 400, 22));

        lblStatusDot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStatusDot.setForeground(new java.awt.Color(76, 175, 80));
        lblStatusDot.setText(".");
        jPanel2.add(lblStatusDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 30, 30));

        lblStatusText.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblStatusText.setForeground(new java.awt.Color(76, 175, 80));
        lblStatusText.setText("CLINIC SYSTEM ONLINE");
        jPanel2.add(lblStatusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 25, -1, -1));

        pnlCustomerContent.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 70));

        lblCustomerTitle.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblCustomerTitle.setForeground(new java.awt.Color(48, 70, 90));
        lblCustomerTitle.setText("Customers");
        pnlCustomerContent.add(lblCustomerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, 400, 40));

        lblCustomerSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblCustomerSubtitle.setForeground(new java.awt.Color(113, 128, 140));
        lblCustomerSubtitle.setText("Register and manage every pet owner in our care.");
        pnlCustomerContent.add(lblCustomerSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, -1, -1));

        jPanel1.add(pnlCustomerContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 1303, 720);
    }// </editor-fold>//GEN-END:initComponents

    // Getters for controller
    public javax.swing.JButton getBtnAdd() { return btnAdd1; }
    public javax.swing.JButton getBtnUpdate() { return btnUpdate1; }
    public javax.swing.JButton getBtnDelete() { return btnDelete1; }
    public javax.swing.JButton getBtnClear() { return btnClear; }
    public javax.swing.JButton getBtnNew() { return btnNewCustomer; }
    public javax.swing.JTable getTable() { return tblCustomers; }
    public javax.swing.JTextField getTxtFullName() { return txtFullName; }
    public javax.swing.JTextField getTxtPhone() { return txtPhone; }
    public javax.swing.JTextField getTxtEmail() { return txtEmail; }
    public javax.swing.JTextField getTxtAddress() { return txtAddress; }
    public javax.swing.JTextField getTxtCustomerId() { return txtCustomerId; }
    public javax.swing.JComboBox<String> getCmbStatus() { return cmbStatus; }

    // Passive readers
    public String getCustomerIdText() { return txtCustomerId.getText().trim(); }
    public String getFullNameText() { return txtFullName.getText().trim(); }
    public String getPhoneText() { return txtPhone.getText().trim(); }
    public String getEmailText() { return txtEmail.getText().trim(); }
    public String getAddressText() { return txtAddress.getText().trim(); }
    public String getStatusText() { return String.valueOf(cmbStatus.getSelectedItem()); }

    // Passive display helpers
    public void setRows(java.util.List<Object[]> rows)
    {
        DefaultTableModel model = (DefaultTableModel) tblCustomers.getModel();
        model.setRowCount(0);
        for (Object[] row : rows)
        {
            model.addRow(row);
        }
    }

    public void setStats(int total, int active, int inactive)
    {
        lblTotalCustomersCount.setText(String.valueOf(total));
        lblActiveCustomersCount.setText(String.valueOf(active));
        lblInactiveCustomersCount.setText(String.valueOf(inactive));
    }

    public void fillForm(String id, String name, String phone, String email, String address, String status)
    {
        txtCustomerId.setText(id);
        txtFullName.setText(name);
        txtPhone.setText(phone);
        txtEmail.setText(email);
        txtAddress.setText(address);
        cmbStatus.setSelectedItem(status);
    }

    public void clearForm()
    {
        fillForm("", "", "", "", "", "Active");
        tblCustomers.clearSelection();
    }

    public String cellText(int row, int col)
    {
        Object v = tblCustomers.getValueAt(row, col);
        return v == null ? "" : v.toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnNewCustomer;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActiveCustomersCount;
    private javax.swing.JLabel lblActiveCustomersIcon;
    private javax.swing.JLabel lblActiveCustomersSubtitle;
    private javax.swing.JLabel lblActiveCustomersTitle;
    private javax.swing.JLabel lblBreadcrumb;
    private javax.swing.JLabel lblClinicName;
    private javax.swing.JLabel lblCustomerDetailsSubtitle;
    private javax.swing.JLabel lblCustomerDetailsTitle;
    private javax.swing.JLabel lblCustomerSubtitle;
    private javax.swing.JLabel lblCustomerTitle;
    private javax.swing.JLabel lblInactiveCustomersCount;
    private javax.swing.JLabel lblInactiveCustomersIcon;
    private javax.swing.JLabel lblInactiveCustomersSubtitle;
    private javax.swing.JLabel lblInactiveCustomersTitle;
    private javax.swing.JLabel lblStatusDot;
    private javax.swing.JLabel lblStatusText;
    private javax.swing.JLabel lblTotalCustomersCount;
    private javax.swing.JLabel lblTotalCustomersIcon;
    private javax.swing.JLabel lblTotalCustomersSubtitle;
    private javax.swing.JLabel lblTotalCustomersTitle;
    private javax.swing.JPanel pnlActiveCustomers;
    private javax.swing.JPanel pnlCustomerContent;
    private javax.swing.JPanel pnlCustomerDetails;
    private javax.swing.JPanel pnlInactiveCustomers;
    private javax.swing.JPanel pnlTotalCustomers;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
