/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Customer;
import model.Pet;
import service.DashboardService;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.List;

public class DashboardForm extends javax.swing.JFrame 
{

    private final DashboardService dashboardService;
    private String loggedInUser;

    public DashboardForm() 
    {
        this("Guest");
    }

    public DashboardForm(String username) 
    {
        initComponents();

        dashboardService = new DashboardService();
        loggedInUser = username;

        setLocationRelativeTo(null);

        lblUserInfo.setText("Signed in as: " + loggedInUser);

        loadCounts();
        loadRecentLists();
        setupButtonActions();

        sidebarPanel1.setNavigationListener(this::handleSidebarNavigation);
    }

    private void loadCounts() 
    {
        lblCustomerCount.setText(String.valueOf(dashboardService.getCustomerCount()));
        lblPetCount.setText(String.valueOf(dashboardService.getPetCount()));
        lblStaffCount.setText(String.valueOf(dashboardService.getStaffCount()));
        lblActiveCustomerCount.setText(String.valueOf(dashboardService.getActiveCustomerCount()));
        lblActiveStaffCount.setText(String.valueOf(dashboardService.getActiveStaffCount()));
    }

    private void loadRecentLists() 
    {
        DefaultListModel<String> customerModel = new DefaultListModel<>();
        List<Customer> recentCustomers = dashboardService.getRecentCustomers();
        for (Customer c : recentCustomers) 
        {
            customerModel.addElement(c.getFullName() + "  (" + c.getStatus() + ")");
        }
        lstRecentCustomers.setModel(customerModel);

        DefaultListModel<String> petModel = new DefaultListModel<>();
        List<Pet> recentPets = dashboardService.getRecentPets();
        for (Pet p : recentPets) 
        {
            petModel.addElement(p.getPetName() + "  -  " + p.getSpecies());
        }
        lstRecentPets.setModel(petModel);
    }

    private void setupButtonActions() 
    {
        btnRegisterCustomer.addActionListener(e -> 
        {
            new CustomerForm().setVisible(true);
            dispose();
        });

        btnAddPet.addActionListener(e -> 
        {
            new PetForm().setVisible(true);
            dispose();
        });

        btnNewAppointment.addActionListener(e -> 
        {
            JOptionPane.showMessageDialog(this,
                "Appointments module coming soon.",
                "Not available yet",
                JOptionPane.INFORMATION_MESSAGE);
        });

        btnRecordPayment.addActionListener(e -> 
        {
            JOptionPane.showMessageDialog(this,
                "Billing module coming soon.",
                "Not available yet",
                JOptionPane.INFORMATION_MESSAGE);
        });
    }

    private void handleSidebarNavigation(String destination) 
    {
        switch (destination) 
        {
            case "Customers":
                new CustomerForm().setVisible(true);
                dispose();
                break;
            case "Pet Patients":
                new PetForm().setVisible(true);
                dispose();
                break;
            default:
                JOptionPane.showMessageDialog(this,
                    destination + " module coming soon.",
                    "Not available yet",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel1 = new view.SidebarPanel();
        pnlDashboardContent = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblUserInfo = new javax.swing.JLabel();
        lblPetTitle = new javax.swing.JLabel();
        lblPetCount = new javax.swing.JLabel();
        lblCustomerTitle1 = new javax.swing.JLabel();
        lblCustomerCount = new javax.swing.JLabel();
        lblStaffTitle = new javax.swing.JLabel();
        lblStaffCount = new javax.swing.JLabel();
        lblActiveCustomerTitle = new javax.swing.JLabel();
        lblActiveCustomerCount = new javax.swing.JLabel();
        lblActiveStaffTitle = new javax.swing.JLabel();
        lblActiveStaffCount = new javax.swing.JLabel();
        lblQuickActions = new javax.swing.JLabel();
        btnNewAppointment = new javax.swing.JButton();
        btnRegisterCustomer = new javax.swing.JButton();
        btnAddPet = new javax.swing.JButton();
        btnRecordPayment = new javax.swing.JButton();
        lblRecentCustomers = new javax.swing.JLabel();
        lblRecentPets = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstRecentCustomers = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstRecentPets = new javax.swing.JList<>();
        pnlCardCustomers = new javax.swing.JPanel();
        pnlCardPets = new javax.swing.JPanel();
        pnlCardStaff = new javax.swing.JPanel();
        pnlCardActiveCustomers = new javax.swing.JPanel();
        pnlCardActiveStaff = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setPreferredSize(new java.awt.Dimension(1500, 900));
        setSize(new java.awt.Dimension(1500, 900));

        sidebarPanel1.setMinimumSize(new java.awt.Dimension(250, 900));
        getContentPane().add(sidebarPanel1, java.awt.BorderLayout.WEST);

        pnlDashboardContent.setBackground(new java.awt.Color(250, 246, 240));
        pnlDashboardContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(74, 91, 106));
        lblWelcome.setText("Welcome to PawCare 360");
        pnlDashboardContent.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 500, 35));

        lblUserInfo.setForeground(new java.awt.Color(110, 125, 135));
        lblUserInfo.setText("Signed in as...");
        pnlDashboardContent.add(lblUserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 400, 20));

        lblPetTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblPetTitle.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        lblPetTitle.setText("PETS");
        pnlDashboardContent.add(lblPetTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 100, 220, 16));

        lblPetCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblPetCount.setForeground(new java.awt.Color(74, 91, 106));
        lblPetCount.setText("0");
        pnlDashboardContent.add(lblPetCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 122, 220, 36));

        lblCustomerTitle1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblCustomerTitle1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        lblCustomerTitle1.setText("CUSTOMERS");
        pnlDashboardContent.add(lblCustomerTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 220, 16));

        lblCustomerCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblCustomerCount.setForeground(new java.awt.Color(74, 91, 106));
        lblCustomerCount.setText("0");
        pnlDashboardContent.add(lblCustomerCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 122, 220, 36));

        lblStaffTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblStaffTitle.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        lblStaffTitle.setText("STAFF");
        pnlDashboardContent.add(lblStaffTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 220, 16));

        lblStaffCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblStaffCount.setForeground(new java.awt.Color(74, 91, 106));
        lblStaffCount.setText("0");
        pnlDashboardContent.add(lblStaffCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 122, 220, 36));

        lblActiveCustomerTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblActiveCustomerTitle.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        lblActiveCustomerTitle.setText("ACTIVE CUSTOMER");
        pnlDashboardContent.add(lblActiveCustomerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 100, 220, 16));

        lblActiveCustomerCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblActiveCustomerCount.setForeground(new java.awt.Color(74, 91, 106));
        lblActiveCustomerCount.setText("0");
        pnlDashboardContent.add(lblActiveCustomerCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 122, 220, 36));

        lblActiveStaffTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblActiveStaffTitle.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        lblActiveStaffTitle.setText("ACTIVE STAFF");
        pnlDashboardContent.add(lblActiveStaffTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 220, 16));

        lblActiveStaffCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblActiveStaffCount.setForeground(new java.awt.Color(74, 91, 106));
        lblActiveStaffCount.setText("0");
        pnlDashboardContent.add(lblActiveStaffCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 122, 220, 36));

        lblQuickActions.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblQuickActions.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        lblQuickActions.setText("QUICK ACTIONS");
        pnlDashboardContent.add(lblQuickActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 300, 25));

        btnNewAppointment.setBackground(new java.awt.Color(157, 201, 163));
        btnNewAppointment.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnNewAppointment.setForeground(new java.awt.Color(74, 91, 106));
        btnNewAppointment.setText("New Appoinment");
        btnNewAppointment.addActionListener(this::btnNewAppointmentActionPerformed);
        pnlDashboardContent.add(btnNewAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 245, 290, 55));

        btnRegisterCustomer.setBackground(new java.awt.Color(157, 201, 163));
        btnRegisterCustomer.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnRegisterCustomer.setForeground(new java.awt.Color(74, 91, 106));
        btnRegisterCustomer.setText("Register Customer");
        btnRegisterCustomer.addActionListener(this::btnRegisterCustomerActionPerformed);
        pnlDashboardContent.add(btnRegisterCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 245, 290, 55));

        btnAddPet.setBackground(new java.awt.Color(157, 201, 163));
        btnAddPet.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAddPet.setForeground(new java.awt.Color(74, 91, 106));
        btnAddPet.setText("Add Pet");
        btnAddPet.addActionListener(this::btnAddPetActionPerformed);
        pnlDashboardContent.add(btnAddPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 245, 290, 55));

        btnRecordPayment.setBackground(new java.awt.Color(157, 201, 163));
        btnRecordPayment.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnRecordPayment.setForeground(new java.awt.Color(74, 91, 106));
        btnRecordPayment.setText("Record Payment");
        btnRecordPayment.addActionListener(this::btnRecordPaymentActionPerformed);
        pnlDashboardContent.add(btnRecordPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 245, 290, 55));

        lblRecentCustomers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRecentCustomers.setText("RECENT CUSTOMERS");
        pnlDashboardContent.add(lblRecentCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 300, 25));

        lblRecentPets.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRecentPets.setText("RECENT PET PATIENTS");
        pnlDashboardContent.add(lblRecentPets, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 300, 25));

        lstRecentCustomers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstRecentCustomers);

        pnlDashboardContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 590, 300));

        lstRecentPets.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstRecentPets);

        pnlDashboardContent.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 590, 300));

        pnlCardCustomers.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardCustomers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        javax.swing.GroupLayout pnlCardCustomersLayout = new javax.swing.GroupLayout(pnlCardCustomers);
        pnlCardCustomers.setLayout(pnlCardCustomersLayout);
        pnlCardCustomersLayout.setHorizontalGroup(
            pnlCardCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        pnlCardCustomersLayout.setVerticalGroup(
            pnlCardCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        pnlDashboardContent.add(pnlCardCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 110));

        pnlCardPets.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardPets.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        javax.swing.GroupLayout pnlCardPetsLayout = new javax.swing.GroupLayout(pnlCardPets);
        pnlCardPets.setLayout(pnlCardPetsLayout);
        pnlCardPetsLayout.setHorizontalGroup(
            pnlCardPetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        pnlCardPetsLayout.setVerticalGroup(
            pnlCardPetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        pnlDashboardContent.add(pnlCardPets, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 220, 110));

        pnlCardStaff.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardStaff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        javax.swing.GroupLayout pnlCardStaffLayout = new javax.swing.GroupLayout(pnlCardStaff);
        pnlCardStaff.setLayout(pnlCardStaffLayout);
        pnlCardStaffLayout.setHorizontalGroup(
            pnlCardStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        pnlCardStaffLayout.setVerticalGroup(
            pnlCardStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        pnlDashboardContent.add(pnlCardStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 220, 110));

        pnlCardActiveCustomers.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardActiveCustomers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        javax.swing.GroupLayout pnlCardActiveCustomersLayout = new javax.swing.GroupLayout(pnlCardActiveCustomers);
        pnlCardActiveCustomers.setLayout(pnlCardActiveCustomersLayout);
        pnlCardActiveCustomersLayout.setHorizontalGroup(
            pnlCardActiveCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        pnlCardActiveCustomersLayout.setVerticalGroup(
            pnlCardActiveCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        pnlDashboardContent.add(pnlCardActiveCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 220, 110));

        pnlCardActiveStaff.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardActiveStaff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        javax.swing.GroupLayout pnlCardActiveStaffLayout = new javax.swing.GroupLayout(pnlCardActiveStaff);
        pnlCardActiveStaff.setLayout(pnlCardActiveStaffLayout);
        pnlCardActiveStaffLayout.setHorizontalGroup(
            pnlCardActiveStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        pnlCardActiveStaffLayout.setVerticalGroup(
            pnlCardActiveStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        pnlDashboardContent.add(pnlCardActiveStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 220, 110));

        getContentPane().add(pnlDashboardContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewAppointmentActionPerformed

    private void btnRegisterCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterCustomerActionPerformed

    private void btnAddPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPetActionPerformed

    private void btnRecordPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecordPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPet;
    private javax.swing.JButton btnNewAppointment;
    private javax.swing.JButton btnRecordPayment;
    private javax.swing.JButton btnRegisterCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblActiveCustomerCount;
    private javax.swing.JLabel lblActiveCustomerTitle;
    private javax.swing.JLabel lblActiveStaffCount;
    private javax.swing.JLabel lblActiveStaffTitle;
    private javax.swing.JLabel lblCustomerCount;
    private javax.swing.JLabel lblCustomerTitle1;
    private javax.swing.JLabel lblPetCount;
    private javax.swing.JLabel lblPetTitle;
    private javax.swing.JLabel lblQuickActions;
    private javax.swing.JLabel lblRecentCustomers;
    private javax.swing.JLabel lblRecentPets;
    private javax.swing.JLabel lblStaffCount;
    private javax.swing.JLabel lblStaffTitle;
    private javax.swing.JLabel lblUserInfo;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList<String> lstRecentCustomers;
    private javax.swing.JList<String> lstRecentPets;
    private javax.swing.JPanel pnlCardActiveCustomers;
    private javax.swing.JPanel pnlCardActiveStaff;
    private javax.swing.JPanel pnlCardCustomers;
    private javax.swing.JPanel pnlCardPets;
    private javax.swing.JPanel pnlCardStaff;
    private javax.swing.JPanel pnlDashboardContent;
    private view.SidebarPanel sidebarPanel1;
    // End of variables declaration//GEN-END:variables
}
