/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.User;
import service.UserService;

import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame 
{

    private final UserService userService;

    public LoginForm() 
    {
        initComponents();
        setResizable(false);
        userService = new UserService();
        setLocationRelativeTo(null);
        lblError.setText(" ");

        btnLogin.addActionListener(e -> handleLogin());
    }

    private void handleLogin() 
    {
        String username = txtUsername.getText().trim();
       String password = txtPassword.getText().trim();

        try 
        {
            User user = userService.login(username, password);

            if (user == null) 
            {
                lblError.setText("Invalid username or password.");
                txtPassword.setText("");
                return;
            }

            new DashboardForm(user.getUsername()).setVisible(true);
            dispose();
        } 
        catch (IllegalArgumentException ex) 
        {
            lblError.setText(ex.getMessage());
        } 
        catch (Exception ex) 
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Unable to connect to the database. Check your XAMPP MySQL is running.",
                "Connection Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUsernameLabel = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PawCare 360 - Login");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblTitle.setText("PawCare 360");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 400, 40));

        lblSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblSubtitle.setText("Veterinary Clinic Management");
        getContentPane().add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 400, 25));

        lblPassword.setForeground(new java.awt.Color(74, 91, 106));
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 400, 20));

        lblUsernameLabel.setForeground(new java.awt.Color(74, 91, 106));
        lblUsernameLabel.setText("Username");
        getContentPane().add(lblUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 400, 20));

        lblError.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblError.setForeground(java.awt.Color.red);
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 400, 20));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 185, 400, 35));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 255, 400, 35));

        btnLogin.setBackground(new java.awt.Color(157, 201, 163));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(74, 91, 106));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 400, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsernameLabel;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
