package view;

import javax.swing.table.DefaultTableModel;

/**
 * Passive service view.
 */
public class ServiceForm extends javax.swing.JFrame {

    public ServiceForm()
    {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Full screen
        setLocationRelativeTo(null);
        readOnlyTable();
    }

    // Cells not editable
    private void readOnlyTable()
    {
        DefaultTableModel old = (DefaultTableModel) tblServices.getModel();
        String[] cols = new String[old.getColumnCount()];
        for (int i = 0; i < cols.length; i++)
        {
            cols[i] = old.getColumnName(i);
        }
        tblServices.setModel(new DefaultTableModel(new Object[0][], cols)
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlServiceContent = new javax.swing.JPanel();
        pnlCardTotal = new javax.swing.JPanel();
        lblTotalTitle = new javax.swing.JLabel();
        lblTotalCount = new javax.swing.JLabel();
        pnlCardActive = new javax.swing.JPanel();
        lblScheduledTitle = new javax.swing.JLabel();
        lblActiveCount = new javax.swing.JLabel();
        pnlCardInactive = new javax.swing.JPanel();
        lblInactiveCount = new javax.swing.JLabel();
        lblInactiveTitle = new javax.swing.JLabel();
        pnlCardCategories = new javax.swing.JPanel();
        lblCategoriesCount = new javax.swing.JLabel();
        lblCategoriesTitle = new javax.swing.JLabel();
        lblPageTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlServiceDetails = new javax.swing.JPanel();
        lblFormSubtitle = new javax.swing.JLabel();
        lblformTitle = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        lblServiceName = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnAddService = new javax.swing.JButton();
        btnUpdateService = new javax.swing.JButton();
        btnDeleteServcie = new javax.swing.JButton();
        btnClearService = new javax.swing.JButton();
        txtServiceName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtDuartion = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        txtCategory = new javax.swing.JTextField();
        lblServiceListTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServices = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setPreferredSize(new java.awt.Dimension(1500, 900));
        setSize(new java.awt.Dimension(1500, 900));

        pnlServiceContent.setBackground(new java.awt.Color(250, 246, 240));
        pnlServiceContent.setMinimumSize(new java.awt.Dimension(1500, 900));
        pnlServiceContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCardTotal.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTotalTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblTotalTitle.setText("TOTAL");
        pnlCardTotal.add(lblTotalTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblTotalCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTotalCount.setForeground(new java.awt.Color(74, 91, 106));
        lblTotalCount.setText("0");
        pnlCardTotal.add(lblTotalCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlServiceContent.add(pnlCardTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 90));

        pnlCardActive.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardActive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardActive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScheduledTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblScheduledTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblScheduledTitle.setText("ACTIVE");
        pnlCardActive.add(lblScheduledTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblActiveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblActiveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblActiveCount.setText("0");
        pnlCardActive.add(lblActiveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlServiceContent.add(pnlCardActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 280, 90));

        pnlCardInactive.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardInactive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardInactive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInactiveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblInactiveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblInactiveCount.setText("0");
        pnlCardInactive.add(lblInactiveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblInactiveTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblInactiveTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblInactiveTitle.setText("INACTIVE");
        pnlCardInactive.add(lblInactiveTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlServiceContent.add(pnlCardInactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 280, 90));

        pnlCardCategories.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardCategories.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardCategories.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCategoriesCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblCategoriesCount.setForeground(new java.awt.Color(74, 91, 106));
        lblCategoriesCount.setText("0");
        pnlCardCategories.add(lblCategoriesCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblCategoriesTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCategoriesTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblCategoriesTitle.setText("CATEGORIES");
        pnlCardCategories.add(lblCategoriesTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlServiceContent.add(pnlCardCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 280, 90));

        lblPageTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPageTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblPageTitle.setText("Services");
        pnlServiceContent.add(lblPageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 35));

        lblSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblSubtitle.setText("Manage clinic services and pricing");
        pnlServiceContent.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 20));

        pnlServiceDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlServiceDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlServiceDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblFormSubtitle.setText("Add and manage services offered");
        pnlServiceDetails.add(lblFormSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, 500, 20));

        lblformTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblformTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblformTitle.setText("SERVICE REGISTRATION");
        pnlServiceDetails.add(lblformTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 25));

        lblDescription.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(113, 128, 140));
        lblDescription.setText("DESCRIPTION");
        pnlServiceDetails.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 366, 18));

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(113, 128, 140));
        lblCategory.setText("CATEGORY");
        pnlServiceDetails.add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 270, 18));

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(113, 128, 140));
        lblPrice.setText("PRICE (LKR)");
        pnlServiceDetails.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 270, 18));

        lblDuration.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDuration.setForeground(new java.awt.Color(113, 128, 140));
        lblDuration.setText("DURATION (MIN)");
        pnlServiceDetails.add(lblDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 270, 18));

        lblServiceName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblServiceName.setForeground(new java.awt.Color(113, 128, 140));
        lblServiceName.setText("SERVICE NAME");
        pnlServiceDetails.add(lblServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, 18));
        pnlServiceDetails.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 750, 32));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(113, 128, 140));
        lblStatus.setText("STATUS");
        pnlServiceDetails.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 160, 366, 18));

        lblMessage.setForeground(java.awt.Color.red);
        pnlServiceDetails.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 600, 20));

        btnAddService.setBackground(new java.awt.Color(157, 201, 163));
        btnAddService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddService.setForeground(new java.awt.Color(74, 91, 106));
        btnAddService.setText("Add Service");
        pnlServiceDetails.add(btnAddService, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, 45));

        btnUpdateService.setBackground(new java.awt.Color(190, 210, 230));
        btnUpdateService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateService.setForeground(new java.awt.Color(74, 91, 106));
        btnUpdateService.setText("Update ");
        pnlServiceDetails.add(btnUpdateService, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 270, 45));

        btnDeleteServcie.setBackground(new java.awt.Color(220, 170, 170));
        btnDeleteServcie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteServcie.setForeground(new java.awt.Color(120, 40, 40));
        btnDeleteServcie.setText("Delete");
        pnlServiceDetails.add(btnDeleteServcie, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 270, 45));

        btnClearService.setBackground(new java.awt.Color(235, 235, 230));
        btnClearService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearService.setForeground(new java.awt.Color(74, 91, 106));
        btnClearService.setText("Clear");
        pnlServiceDetails.add(btnClearService, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 270, 45));
        pnlServiceDetails.add(txtServiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 32));
        pnlServiceDetails.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 270, 32));
        pnlServiceDetails.add(txtDuartion, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 270, 32));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlServiceDetails.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 180, 366, 32));
        pnlServiceDetails.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 270, 32));

        pnlServiceContent.add(pnlServiceDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1180, 340));

        lblServiceListTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblServiceListTitle.setForeground(new java.awt.Color(113, 128, 140));
        lblServiceListTitle.setText("ALL SERVICES");
        pnlServiceContent.add(lblServiceListTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 400, 25));

        tblServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Service Name", "Category", "Price", "Duration (min)", "Description", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblServices);

        pnlServiceContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 1180, 160));

        getContentPane().add(pnlServiceContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Getters for controller
    public javax.swing.JButton getBtnAdd() { return btnAddService; }
    public javax.swing.JButton getBtnUpdate() { return btnUpdateService; }
    public javax.swing.JButton getBtnDelete() { return btnDeleteServcie; }
    public javax.swing.JButton getBtnClear() { return btnClearService; }
    public javax.swing.JTable getTable() { return tblServices; }
    public javax.swing.JTextField getTxtServiceName() { return txtServiceName; }
    public javax.swing.JTextField getTxtCategory() { return txtCategory; }
    public javax.swing.JTextField getTxtPrice() { return txtPrice; }
    public javax.swing.JTextField getTxtDuration() { return txtDuartion; }
    public javax.swing.JTextField getTxtDescription() { return txtDescription; }
    public javax.swing.JComboBox<String> getCmbStatus() { return cmbStatus; }

    // Passive readers
    public String getServiceNameText() { return txtServiceName.getText().trim(); }
    public String getCategoryText() { return txtCategory.getText().trim(); }
    public String getPriceText() { return txtPrice.getText().trim(); }
    public String getDurationText() { return txtDuartion.getText().trim(); }
    public String getDescriptionText() { return txtDescription.getText().trim(); }
    public String getStatusText() { return String.valueOf(cmbStatus.getSelectedItem()); }

    // Passive display helpers
    public void setRows(java.util.List<Object[]> rows)
    {
        DefaultTableModel model = (DefaultTableModel) tblServices.getModel();
        model.setRowCount(0);
        for (Object[] row : rows)
        {
            model.addRow(row);
        }
    }

    public void setStats(long total, long active, long inactive, long categories)
    {
        lblTotalCount.setText(String.valueOf(total));
        lblActiveCount.setText(String.valueOf(active));
        lblInactiveCount.setText(String.valueOf(inactive));
        lblCategoriesCount.setText(String.valueOf(categories));
    }

    public void fillForm(String name, String category, String price, String duration,
            String description, String status)
    {
        txtServiceName.setText(name);
        txtCategory.setText(category);
        txtPrice.setText(price);
        txtDuartion.setText(duration);
        txtDescription.setText(description);
        cmbStatus.setSelectedItem(status);
    }

    public void clearForm()
    {
        fillForm("", "", "", "", "", "Active");
        tblServices.clearSelection();
    }

    public String cellText(int row, int col)
    {
        Object v = tblServices.getValueAt(row, col);
        return v == null ? "" : v.toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnClearService;
    private javax.swing.JButton btnDeleteServcie;
    private javax.swing.JButton btnUpdateService;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActiveCount;
    private javax.swing.JLabel lblCategoriesCount;
    private javax.swing.JLabel lblCategoriesTitle;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblFormSubtitle;
    private javax.swing.JLabel lblInactiveCount;
    private javax.swing.JLabel lblInactiveTitle;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblScheduledTitle;
    private javax.swing.JLabel lblServiceListTitle;
    private javax.swing.JLabel lblServiceName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTotalCount;
    private javax.swing.JLabel lblTotalTitle;
    private javax.swing.JLabel lblformTitle;
    private javax.swing.JPanel pnlCardActive;
    private javax.swing.JPanel pnlCardCategories;
    private javax.swing.JPanel pnlCardInactive;
    private javax.swing.JPanel pnlCardTotal;
    private javax.swing.JPanel pnlServiceContent;
    private javax.swing.JPanel pnlServiceDetails;
    private javax.swing.JTable tblServices;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtDuartion;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtServiceName;
    // End of variables declaration//GEN-END:variables
}
