package view;

import javax.swing.table.DefaultTableModel;

/**
 * Passive staff view.
 */
public class StaffForm extends javax.swing.JFrame {

    public StaffForm()
    {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Full screen
        setLocationRelativeTo(null);
        readOnlyTable();
    }

    // Cells not editable
    private void readOnlyTable()
    {
        DefaultTableModel old = (DefaultTableModel) tblStaff.getModel();
        String[] cols = new String[old.getColumnCount()];
        for (int i = 0; i < cols.length; i++)
        {
            cols[i] = old.getColumnName(i);
        }
        tblStaff.setModel(new DefaultTableModel(new Object[0][], cols)
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStaffContent = new javax.swing.JPanel();
        pnlCardTotal = new javax.swing.JPanel();
        lblTotalTitle = new javax.swing.JLabel();
        lblTotalCount = new javax.swing.JLabel();
        pnlCardActive = new javax.swing.JPanel();
        lblScheduledTitle = new javax.swing.JLabel();
        lblActiveCount = new javax.swing.JLabel();
        pnlCardOnLeave = new javax.swing.JPanel();
        lblOnLeaveCount = new javax.swing.JLabel();
        lblOnLeaveTitle = new javax.swing.JLabel();
        pnlCardInactive = new javax.swing.JPanel();
        lblInactiveCount = new javax.swing.JLabel();
        lblInactiveTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlStaffDetails = new javax.swing.JPanel();
        lblFormSubtitle = new javax.swing.JLabel();
        lblformTitle = new javax.swing.JLabel();
        lblSpecialization = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        txtSpecialization = new javax.swing.JTextField();
        lblHireDate = new javax.swing.JLabel();
        txtHireDate = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnAddStaff = new javax.swing.JButton();
        btnUpdateStaff = new javax.swing.JButton();
        btnDeleteStaff = new javax.swing.JButton();
        btnClearStaff = new javax.swing.JButton();
        txtFullName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        lblStaffListTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setSize(new java.awt.Dimension(1500, 900));

        pnlStaffContent.setBackground(new java.awt.Color(250, 246, 240));
        pnlStaffContent.setMinimumSize(new java.awt.Dimension(1500, 900));
        pnlStaffContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCardTotal.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTotalTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblTotalTitle.setText("TOTAL");
        pnlCardTotal.add(lblTotalTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblTotalCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTotalCount.setForeground(new java.awt.Color(74, 91, 106));
        lblTotalCount.setText("0");
        pnlCardTotal.add(lblTotalCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlStaffContent.add(pnlCardTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 90));

        pnlCardActive.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardActive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardActive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScheduledTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblScheduledTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblScheduledTitle.setText("ACTIVE");
        pnlCardActive.add(lblScheduledTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblActiveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblActiveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblActiveCount.setText("0");
        pnlCardActive.add(lblActiveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlStaffContent.add(pnlCardActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 280, 90));

        pnlCardOnLeave.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardOnLeave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardOnLeave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOnLeaveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblOnLeaveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblOnLeaveCount.setText("0");
        pnlCardOnLeave.add(lblOnLeaveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblOnLeaveTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblOnLeaveTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblOnLeaveTitle.setText("ON LEAVE");
        pnlCardOnLeave.add(lblOnLeaveTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlStaffContent.add(pnlCardOnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 280, 90));

        pnlCardInactive.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardInactive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardInactive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInactiveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblInactiveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblInactiveCount.setText("0");
        pnlCardInactive.add(lblInactiveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblInactiveTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblInactiveTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblInactiveTitle.setText("INACTIVE");
        pnlCardInactive.add(lblInactiveTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlStaffContent.add(pnlCardInactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 280, 90));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblTitle.setText("Staff");
        pnlStaffContent.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 35));

        lblSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblSubtitle.setText("Manage clinic staff records");
        pnlStaffContent.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 20));

        pnlStaffDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlStaffDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlStaffDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblFormSubtitle.setText("Register and manage staff records");
        pnlStaffDetails.add(lblFormSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, 500, 20));

        lblformTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblformTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblformTitle.setText("STAFF REGISTRATION");
        pnlStaffDetails.add(lblformTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 25));

        lblSpecialization.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblSpecialization.setForeground(new java.awt.Color(113, 128, 140));
        lblSpecialization.setText("SPECIALIZATION");
        pnlStaffDetails.add(lblSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 366, 18));

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblRole.setForeground(new java.awt.Color(113, 128, 140));
        lblRole.setText("ROLE");
        pnlStaffDetails.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 270, 18));

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlStaffDetails.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 270, 32));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(113, 128, 140));
        lblPhone.setText("PHONE");
        pnlStaffDetails.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 270, 18));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(113, 128, 140));
        lblEmail.setText("EMAIL");
        pnlStaffDetails.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 270, 18));

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(113, 128, 140));
        lblFullName.setText("FULL NAME");
        pnlStaffDetails.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, 18));
        pnlStaffDetails.add(txtSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 366, 32));

        lblHireDate.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblHireDate.setForeground(new java.awt.Color(113, 128, 140));
        lblHireDate.setText("HIRE DATE (YYYY-MM-DD)");
        pnlStaffDetails.add(lblHireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 160, 366, 18));
        pnlStaffDetails.add(txtHireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 180, 366, 32));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(113, 128, 140));
        lblStatus.setText("STATUS");
        pnlStaffDetails.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 160, 366, 18));

        lblMessage.setForeground(java.awt.Color.red);
        pnlStaffDetails.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 600, 20));

        btnAddStaff.setBackground(new java.awt.Color(157, 201, 163));
        btnAddStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddStaff.setForeground(new java.awt.Color(74, 91, 106));
        btnAddStaff.setText("Add Staff");
        pnlStaffDetails.add(btnAddStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, 45));

        btnUpdateStaff.setBackground(new java.awt.Color(190, 210, 230));
        btnUpdateStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateStaff.setForeground(new java.awt.Color(74, 91, 106));
        btnUpdateStaff.setText("Update ");
        pnlStaffDetails.add(btnUpdateStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 270, 45));

        btnDeleteStaff.setBackground(new java.awt.Color(220, 170, 170));
        btnDeleteStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteStaff.setForeground(new java.awt.Color(120, 40, 40));
        btnDeleteStaff.setText("Delete");
        pnlStaffDetails.add(btnDeleteStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 270, 45));

        btnClearStaff.setBackground(new java.awt.Color(235, 235, 230));
        btnClearStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearStaff.setForeground(new java.awt.Color(74, 91, 106));
        btnClearStaff.setText("Clear");
        pnlStaffDetails.add(btnClearStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 270, 45));
        pnlStaffDetails.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 32));
        pnlStaffDetails.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 270, 32));
        pnlStaffDetails.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 270, 32));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlStaffDetails.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 180, 366, 32));

        pnlStaffContent.add(pnlStaffDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1180, 340));

        lblStaffListTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStaffListTitle.setForeground(new java.awt.Color(113, 128, 140));
        lblStaffListTitle.setText("ALL STAFF");
        pnlStaffContent.add(lblStaffListTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 400, 25));

        tblStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "Role", "Phone", "Email", "Specialization", "Hire Date", "Status"
            }
        ));
        tblStaff.setRowHeight(28);
        jScrollPane1.setViewportView(tblStaff);

        pnlStaffContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 1180, 250));

        getContentPane().add(pnlStaffContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Getters for controller
    public javax.swing.JButton getBtnAdd() { return btnAddStaff; }
    public javax.swing.JButton getBtnUpdate() { return btnUpdateStaff; }
    public javax.swing.JButton getBtnDelete() { return btnDeleteStaff; }
    public javax.swing.JButton getBtnClear() { return btnClearStaff; }
    public javax.swing.JTable getTable() { return tblStaff; }
    public javax.swing.JTextField getTxtFullName() { return txtFullName; }
    public javax.swing.JTextField getTxtPhone() { return txtPhone; }
    public javax.swing.JTextField getTxtEmail() { return txtEmail; }
    public javax.swing.JTextField getTxtSpecialization() { return txtSpecialization; }
    public javax.swing.JTextField getTxtHireDate() { return txtHireDate; }
    public javax.swing.JComboBox<String> getCmbRole() { return cmbRole; }
    public javax.swing.JComboBox<String> getCmbStatus() { return cmbStatus; }

    // Passive readers
    public String getFullNameText() { return txtFullName.getText().trim(); }
    public String getRoleText() { return String.valueOf(cmbRole.getSelectedItem()); }
    public String getPhoneText() { return txtPhone.getText().trim(); }
    public String getEmailText() { return txtEmail.getText().trim(); }
    public String getSpecializationText() { return txtSpecialization.getText().trim(); }
    public String getHireDateText() { return txtHireDate.getText().trim(); }
    public String getStatusText() { return String.valueOf(cmbStatus.getSelectedItem()); }

    // Passive display helpers
    public void setRows(java.util.List<Object[]> rows)
    {
        DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();
        model.setRowCount(0);
        for (Object[] row : rows)
        {
            model.addRow(row);
        }
    }

    public void setStats(long total, long active, long onLeave, long inactive)
    {
        lblTotalCount.setText(String.valueOf(total));
        lblActiveCount.setText(String.valueOf(active));
        lblOnLeaveCount.setText(String.valueOf(onLeave));
        lblInactiveCount.setText(String.valueOf(inactive));
    }

    public void fillForm(String name, String role, String phone, String email,
            String specialization, String hireDate, String status)
    {
        txtFullName.setText(name);
        cmbRole.setSelectedItem(role);
        txtPhone.setText(phone);
        txtEmail.setText(email);
        txtSpecialization.setText(specialization);
        txtHireDate.setText(hireDate);
        cmbStatus.setSelectedItem(status);
    }

    public void clearForm()
    {
        txtFullName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtSpecialization.setText("");
        txtHireDate.setText("");
        cmbRole.setSelectedIndex(0);
        cmbStatus.setSelectedIndex(0);
        tblStaff.clearSelection();
    }

    public String cellText(int row, int col)
    {
        Object v = tblStaff.getValueAt(row, col);
        return v == null ? "" : v.toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnClearStaff;
    private javax.swing.JButton btnDeleteStaff;
    private javax.swing.JButton btnUpdateStaff;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActiveCount;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFormSubtitle;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblHireDate;
    private javax.swing.JLabel lblInactiveCount;
    private javax.swing.JLabel lblInactiveTitle;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblOnLeaveCount;
    private javax.swing.JLabel lblOnLeaveTitle;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblScheduledTitle;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblStaffListTitle;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCount;
    private javax.swing.JLabel lblTotalTitle;
    private javax.swing.JLabel lblformTitle;
    private javax.swing.JPanel pnlCardActive;
    private javax.swing.JPanel pnlCardInactive;
    private javax.swing.JPanel pnlCardOnLeave;
    private javax.swing.JPanel pnlCardTotal;
    private javax.swing.JPanel pnlStaffContent;
    private javax.swing.JPanel pnlStaffDetails;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtHireDate;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSpecialization;
    // End of variables declaration//GEN-END:variables
}
