/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author HP
 */
public class StaffForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffForm.class.getName());

    /**
     * Creates new form StaffForm
     */
    public StaffForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel1 = new view.SidebarPanel();
        pnlStaffContent = new javax.swing.JPanel();
        pnlCardTotal = new javax.swing.JPanel();
        lblTotalTitle = new javax.swing.JLabel();
        lblTotalCount = new javax.swing.JLabel();
        pnlCardActive = new javax.swing.JPanel();
        lblScheduledTitle = new javax.swing.JLabel();
        lblActiveCount = new javax.swing.JLabel();
        pnlCardOnLeave = new javax.swing.JPanel();
        lblOnLeaveCount = new javax.swing.JLabel();
        lblOnLeaveTitle = new javax.swing.JLabel();
        pnlCardInactive = new javax.swing.JPanel();
        lblInactiveCount = new javax.swing.JLabel();
        lblInactiveTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlStaffDetails = new javax.swing.JPanel();
        lblFormSubtitle = new javax.swing.JLabel();
        lblformTitle = new javax.swing.JLabel();
        lblSpecialization = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        txtSpecialization = new javax.swing.JTextField();
        lblHireDate = new javax.swing.JLabel();
        txtHireDate = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnAddStaff = new javax.swing.JButton();
        btnUpdateStaff = new javax.swing.JButton();
        btnDeleteStaff = new javax.swing.JButton();
        btnClearStaff = new javax.swing.JButton();
        txtFullName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        lblStaffListTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setSize(new java.awt.Dimension(1500, 900));
        getContentPane().add(sidebarPanel1, java.awt.BorderLayout.WEST);

        pnlStaffContent.setBackground(new java.awt.Color(250, 246, 240));
        pnlStaffContent.setMinimumSize(new java.awt.Dimension(1500, 900));
        pnlStaffContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCardTotal.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTotalTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblTotalTitle.setText("TOTAL");
        pnlCardTotal.add(lblTotalTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblTotalCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTotalCount.setForeground(new java.awt.Color(74, 91, 106));
        lblTotalCount.setText("0");
        pnlCardTotal.add(lblTotalCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlStaffContent.add(pnlCardTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 90));

        pnlCardActive.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardActive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardActive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScheduledTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblScheduledTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblScheduledTitle.setText("ACTIVE");
        pnlCardActive.add(lblScheduledTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblActiveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblActiveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblActiveCount.setText("0");
        pnlCardActive.add(lblActiveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlStaffContent.add(pnlCardActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 280, 90));

        pnlCardOnLeave.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardOnLeave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardOnLeave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOnLeaveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblOnLeaveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblOnLeaveCount.setText("0");
        pnlCardOnLeave.add(lblOnLeaveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblOnLeaveTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblOnLeaveTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblOnLeaveTitle.setText("ON LEAVE");
        pnlCardOnLeave.add(lblOnLeaveTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlStaffContent.add(pnlCardOnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 280, 90));

        pnlCardInactive.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardInactive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardInactive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInactiveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblInactiveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblInactiveCount.setText("0");
        pnlCardInactive.add(lblInactiveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblInactiveTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblInactiveTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblInactiveTitle.setText("INACTIVE");
        pnlCardInactive.add(lblInactiveTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlStaffContent.add(pnlCardInactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 280, 90));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblTitle.setText("Staff");
        pnlStaffContent.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 35));

        lblSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblSubtitle.setText("Manage clinic staff records");
        pnlStaffContent.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 20));

        pnlStaffDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlStaffDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlStaffDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblFormSubtitle.setText("Register and manage staff records");
        pnlStaffDetails.add(lblFormSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, 500, 20));

        lblformTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblformTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblformTitle.setText("STAFF REGISTRATION");
        pnlStaffDetails.add(lblformTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 25));

        lblSpecialization.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblSpecialization.setForeground(new java.awt.Color(113, 128, 140));
        lblSpecialization.setText("SPECIALIZATION");
        pnlStaffDetails.add(lblSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 366, 18));

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblRole.setForeground(new java.awt.Color(113, 128, 140));
        lblRole.setText("ROLE");
        pnlStaffDetails.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 270, 18));

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlStaffDetails.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 270, 32));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(113, 128, 140));
        lblPhone.setText("PHONE");
        pnlStaffDetails.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 270, 18));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(113, 128, 140));
        lblEmail.setText("EMAIL");
        pnlStaffDetails.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 270, 18));

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(113, 128, 140));
        lblFullName.setText("FULL NAME");
        pnlStaffDetails.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, 18));

        txtSpecialization.addActionListener(this::txtSpecializationActionPerformed);
        pnlStaffDetails.add(txtSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 366, 32));

        lblHireDate.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblHireDate.setForeground(new java.awt.Color(113, 128, 140));
        lblHireDate.setText("HIRE DATE (YYYY-MM-DD)");
        pnlStaffDetails.add(lblHireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 160, 366, 18));

        txtHireDate.addActionListener(this::txtHireDateActionPerformed);
        pnlStaffDetails.add(txtHireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 180, 366, 32));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(113, 128, 140));
        lblStatus.setText("STATUS");
        pnlStaffDetails.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 160, 366, 18));

        lblMessage.setForeground(java.awt.Color.red);
        pnlStaffDetails.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 600, 20));

        btnAddStaff.setBackground(new java.awt.Color(157, 201, 163));
        btnAddStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddStaff.setForeground(new java.awt.Color(74, 91, 106));
        btnAddStaff.setText("Add Staff");
        btnAddStaff.addActionListener(this::btnAddStaffActionPerformed);
        pnlStaffDetails.add(btnAddStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, 45));

        btnUpdateStaff.setBackground(new java.awt.Color(190, 210, 230));
        btnUpdateStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateStaff.setForeground(new java.awt.Color(74, 91, 106));
        btnUpdateStaff.setText("Update ");
        btnUpdateStaff.addActionListener(this::btnUpdateStaffActionPerformed);
        pnlStaffDetails.add(btnUpdateStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 270, 45));

        btnDeleteStaff.setBackground(new java.awt.Color(220, 170, 170));
        btnDeleteStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteStaff.setForeground(new java.awt.Color(120, 40, 40));
        btnDeleteStaff.setText("Delete");
        btnDeleteStaff.addActionListener(this::btnDeleteStaffActionPerformed);
        pnlStaffDetails.add(btnDeleteStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 270, 45));

        btnClearStaff.setBackground(new java.awt.Color(235, 235, 230));
        btnClearStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearStaff.setForeground(new java.awt.Color(74, 91, 106));
        btnClearStaff.setText("Clear");
        btnClearStaff.addActionListener(this::btnClearStaffActionPerformed);
        pnlStaffDetails.add(btnClearStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 270, 45));
        pnlStaffDetails.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 32));
        pnlStaffDetails.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 270, 32));
        pnlStaffDetails.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 270, 32));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlStaffDetails.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 180, 366, 32));

        pnlStaffContent.add(pnlStaffDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1180, 340));

        lblStaffListTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStaffListTitle.setForeground(new java.awt.Color(113, 128, 140));
        lblStaffListTitle.setText("ALL STAFF");
        pnlStaffContent.add(lblStaffListTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 400, 25));

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "Role", "Phone", "Email", "Specialization", "Hire Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblStaff);

        pnlStaffContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 1180, 160));

        getContentPane().add(pnlStaffContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecializationActionPerformed

    private void txtHireDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHireDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHireDateActionPerformed

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void btnUpdateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateStaffActionPerformed

    private void btnDeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStaffActionPerformed

    private void btnClearStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnClearStaff;
    private javax.swing.JButton btnDeleteStaff;
    private javax.swing.JButton btnUpdateStaff;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActiveCount;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFormSubtitle;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblHireDate;
    private javax.swing.JLabel lblInactiveCount;
    private javax.swing.JLabel lblInactiveTitle;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblOnLeaveCount;
    private javax.swing.JLabel lblOnLeaveTitle;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblScheduledTitle;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblStaffListTitle;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCount;
    private javax.swing.JLabel lblTotalTitle;
    private javax.swing.JLabel lblformTitle;
    private javax.swing.JPanel pnlCardActive;
    private javax.swing.JPanel pnlCardInactive;
    private javax.swing.JPanel pnlCardOnLeave;
    private javax.swing.JPanel pnlCardTotal;
    private javax.swing.JPanel pnlStaffContent;
    private javax.swing.JPanel pnlStaffDetails;
    private view.SidebarPanel sidebarPanel1;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtHireDate;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSpecialization;
    // End of variables declaration//GEN-END:variables
}
