/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author HP
 */
public class StaffForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffForm.class.getName());

    /**
     * Creates new form StaffForm
     */
    public StaffForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel1 = new view.SidebarPanel();
        pnlStaffContent = new javax.swing.JPanel();
        pnlCardTotal = new javax.swing.JPanel();
        lblTotalTitle = new javax.swing.JLabel();
        lblTotalCount = new javax.swing.JLabel();
        pnlCardActive = new javax.swing.JPanel();
        lblScheduledTitle = new javax.swing.JLabel();
        lblActiveCount = new javax.swing.JLabel();
        pnlCardOnLeave = new javax.swing.JPanel();
        lblOnLeaveCount = new javax.swing.JLabel();
        lblOnLeaveTitle = new javax.swing.JLabel();
        pnlCardInactive = new javax.swing.JPanel();
        lblInactiveCount = new javax.swing.JLabel();
        lblInactiveTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlAppointmentDetails = new javax.swing.JPanel();
        lblFormSubtitle = new javax.swing.JLabel();
        lblformTitle = new javax.swing.JLabel();
        lblDateLabel = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        lblStaffLabel = new javax.swing.JLabel();
        cmbStaff = new javax.swing.JComboBox<>();
        lblServiceLabel = new javax.swing.JLabel();
        cmbService = new javax.swing.JComboBox<>();
        lblFullName = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblTimeTable = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        lblReasonLabel = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        txtNotes = new javax.swing.JTextField();
        lblNotes = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancelAppointment = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtFullName = new javax.swing.JTextField();
        lblRecentsAppointments = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setSize(new java.awt.Dimension(1500, 900));
        getContentPane().add(sidebarPanel1, java.awt.BorderLayout.WEST);

        pnlStaffContent.setBackground(new java.awt.Color(250, 246, 240));
        pnlStaffContent.setMinimumSize(new java.awt.Dimension(1500, 900));
        pnlStaffContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCardTotal.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTotalTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblTotalTitle.setText("TOTAL");
        pnlCardTotal.add(lblTotalTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblTotalCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTotalCount.setForeground(new java.awt.Color(74, 91, 106));
        lblTotalCount.setText("0");
        pnlCardTotal.add(lblTotalCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlStaffContent.add(pnlCardTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 90));

        pnlCardActive.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardActive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardActive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScheduledTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblScheduledTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblScheduledTitle.setText("ACTIVE");
        pnlCardActive.add(lblScheduledTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblActiveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblActiveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblActiveCount.setText("0");
        pnlCardActive.add(lblActiveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlStaffContent.add(pnlCardActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 280, 90));

        pnlCardOnLeave.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardOnLeave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardOnLeave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOnLeaveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblOnLeaveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblOnLeaveCount.setText("0");
        pnlCardOnLeave.add(lblOnLeaveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblOnLeaveTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblOnLeaveTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblOnLeaveTitle.setText("ON LEAVE");
        pnlCardOnLeave.add(lblOnLeaveTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlStaffContent.add(pnlCardOnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 280, 90));

        pnlCardInactive.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardInactive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardInactive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInactiveCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblInactiveCount.setForeground(new java.awt.Color(74, 91, 106));
        lblInactiveCount.setText("0");
        pnlCardInactive.add(lblInactiveCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblInactiveTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblInactiveTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblInactiveTitle.setText("INACTIVE");
        pnlCardInactive.add(lblInactiveTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlStaffContent.add(pnlCardInactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 280, 90));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblTitle.setText("Staff");
        pnlStaffContent.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 35));

        lblSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblSubtitle.setText("Manage clinic staff records");
        pnlStaffContent.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 20));

        pnlAppointmentDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlAppointmentDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlAppointmentDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblFormSubtitle.setText("Register and manage staff records");
        pnlAppointmentDetails.add(lblFormSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, 500, 20));

        lblformTitle.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblformTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblformTitle.setText("STAFF REGISTRATION");
        pnlAppointmentDetails.add(lblformTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 25));

        lblDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDateLabel.setForeground(new java.awt.Color(113, 128, 140));
        lblDateLabel.setText("DATE (YYYY-MM-DD)");
        pnlAppointmentDetails.add(lblDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 366, 18));

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblRole.setForeground(new java.awt.Color(113, 128, 140));
        lblRole.setText("ROLE");
        pnlAppointmentDetails.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 270, 18));

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAppointmentDetails.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 270, 32));

        lblStaffLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStaffLabel.setForeground(new java.awt.Color(113, 128, 140));
        lblStaffLabel.setText("PHONE");
        pnlAppointmentDetails.add(lblStaffLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 270, 18));

        cmbStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAppointmentDetails.add(cmbStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 270, 32));

        lblServiceLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblServiceLabel.setForeground(new java.awt.Color(113, 128, 140));
        lblServiceLabel.setText("SERVICE");
        pnlAppointmentDetails.add(lblServiceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 270, 18));

        cmbService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAppointmentDetails.add(cmbService, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 270, 32));

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(113, 128, 140));
        lblFullName.setText("FULL NAME");
        pnlAppointmentDetails.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, 18));

        txtDate.addActionListener(this::txtDateActionPerformed);
        pnlAppointmentDetails.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 366, 32));

        lblTimeTable.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTimeTable.setForeground(new java.awt.Color(113, 128, 140));
        lblTimeTable.setText("TIME (HH:MM)");
        pnlAppointmentDetails.add(lblTimeTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 160, 366, 18));

        txtTime.addActionListener(this::txtTimeActionPerformed);
        pnlAppointmentDetails.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 180, 366, 32));

        lblReasonLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblReasonLabel.setForeground(new java.awt.Color(113, 128, 140));
        lblReasonLabel.setText("REASON");
        pnlAppointmentDetails.add(lblReasonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 160, 366, 18));

        txtReason.addActionListener(this::txtReasonActionPerformed);
        pnlAppointmentDetails.add(txtReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 180, 366, 32));
        pnlAppointmentDetails.add(txtNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 1140, 70));

        lblNotes.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblNotes.setForeground(new java.awt.Color(113, 128, 140));
        lblNotes.setText("NOTES");
        pnlAppointmentDetails.add(lblNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1140, 18));

        lblMessage.setForeground(java.awt.Color.red);
        pnlAppointmentDetails.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 600, 20));

        btnBook.setBackground(new java.awt.Color(157, 201, 163));
        btnBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBook.setForeground(new java.awt.Color(74, 91, 106));
        btnBook.setText("Book Appointment");
        btnBook.addActionListener(this::btnBookActionPerformed);
        pnlAppointmentDetails.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 355, 270, 45));

        btnUpdate.setBackground(new java.awt.Color(190, 210, 230));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(74, 91, 106));
        btnUpdate.setText("Update Status");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        pnlAppointmentDetails.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 355, 270, 45));

        btnCancelAppointment.setBackground(new java.awt.Color(220, 170, 170));
        btnCancelAppointment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelAppointment.setForeground(new java.awt.Color(120, 40, 40));
        btnCancelAppointment.setText("Cancel");
        btnCancelAppointment.addActionListener(this::btnCancelAppointmentActionPerformed);
        pnlAppointmentDetails.add(btnCancelAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 355, 270, 45));

        btnClear.setBackground(new java.awt.Color(235, 235, 230));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(74, 91, 106));
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        pnlAppointmentDetails.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 355, 270, 45));
        pnlAppointmentDetails.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 32));

        pnlStaffContent.add(pnlAppointmentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1180, 420));

        lblRecentsAppointments.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblRecentsAppointments.setForeground(new java.awt.Color(113, 128, 140));
        lblRecentsAppointments.setText("RECENT APPOINTMENTS");
        pnlStaffContent.add(lblRecentsAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 400, 25));

        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Customer", "Pet", "Staff", "Service", "Date & Time", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblAppointments);

        pnlStaffContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 658, 1180, 160));

        getContentPane().add(pnlStaffContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReasonActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelAppointmentActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancelAppointment;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbService;
    private javax.swing.JComboBox<String> cmbStaff;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActiveCount;
    private javax.swing.JLabel lblDateLabel;
    private javax.swing.JLabel lblFormSubtitle;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblInactiveCount;
    private javax.swing.JLabel lblInactiveTitle;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblOnLeaveCount;
    private javax.swing.JLabel lblOnLeaveTitle;
    private javax.swing.JLabel lblReasonLabel;
    private javax.swing.JLabel lblRecentsAppointments;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblScheduledTitle;
    private javax.swing.JLabel lblServiceLabel;
    private javax.swing.JLabel lblStaffLabel;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTimeTable;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCount;
    private javax.swing.JLabel lblTotalTitle;
    private javax.swing.JLabel lblformTitle;
    private javax.swing.JPanel pnlAppointmentDetails;
    private javax.swing.JPanel pnlCardActive;
    private javax.swing.JPanel pnlCardInactive;
    private javax.swing.JPanel pnlCardOnLeave;
    private javax.swing.JPanel pnlCardTotal;
    private javax.swing.JPanel pnlStaffContent;
    private view.SidebarPanel sidebarPanel1;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtReason;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
