/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author HP
 */
public class TreatmentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TreatmentForm.class.getName());

    /**
     * Creates new form TreatmentForm
     */
    public TreatmentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel1 = new view.SidebarPanel();
        pnlTreatmentContent = new javax.swing.JPanel();
        pnlCardTotal = new javax.swing.JPanel();
        lblTotalTitle = new javax.swing.JLabel();
        lblTotalCount = new javax.swing.JLabel();
        pnlCardToday = new javax.swing.JPanel();
        lblTodayTitle = new javax.swing.JLabel();
        lblTodayCount = new javax.swing.JLabel();
        pnlCardThisWeek = new javax.swing.JPanel();
        lblThisWeekCount = new javax.swing.JLabel();
        lblThisWeekTitle = new javax.swing.JLabel();
        pnlCardThisMonth = new javax.swing.JPanel();
        lblThisMonthCount = new javax.swing.JLabel();
        lblThisMonthTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlTreatmentDetails = new javax.swing.JPanel();
        lblFormSubtitle = new javax.swing.JLabel();
        lblformTitle = new javax.swing.JLabel();
        lblTreatmentDetails = new javax.swing.JLabel();
        cmbAppointment = new javax.swing.JComboBox<>();
        lblStaff = new javax.swing.JLabel();
        cmbStaff = new javax.swing.JComboBox<>();
        lblDiagnosis = new javax.swing.JLabel();
        lblTreatmentDate = new javax.swing.JLabel();
        lblAppointment = new javax.swing.JLabel();
        lblNotes = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnAddTreatment = new javax.swing.JButton();
        btnUpdateTreatment = new javax.swing.JButton();
        btnDeleteTreatment = new javax.swing.JButton();
        btnClearTreatment = new javax.swing.JButton();
        txtDiagnosis = new javax.swing.JTextField();
        txtTreatmentDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTreatmentDetails = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblTreatmentListTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTreatments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 900));
        setSize(new java.awt.Dimension(1500, 900));
        getContentPane().add(sidebarPanel1, java.awt.BorderLayout.WEST);

        pnlTreatmentContent.setBackground(new java.awt.Color(250, 246, 240));
        pnlTreatmentContent.setMinimumSize(new java.awt.Dimension(1200, 900));
        pnlTreatmentContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCardTotal.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTotalTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblTotalTitle.setText("TOTAL");
        pnlCardTotal.add(lblTotalTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblTotalCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTotalCount.setForeground(new java.awt.Color(74, 91, 106));
        lblTotalCount.setText("0");
        pnlCardTotal.add(lblTotalCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlTreatmentContent.add(pnlCardTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 90));

        pnlCardToday.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardToday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardToday.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTodayTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTodayTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblTodayTitle.setText("TODAY");
        pnlCardToday.add(lblTodayTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        lblTodayCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTodayCount.setForeground(new java.awt.Color(74, 91, 106));
        lblTodayCount.setText("0");
        pnlCardToday.add(lblTodayCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        pnlTreatmentContent.add(pnlCardToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 280, 90));

        pnlCardThisWeek.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardThisWeek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardThisWeek.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThisWeekCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblThisWeekCount.setForeground(new java.awt.Color(74, 91, 106));
        lblThisWeekCount.setText("0");
        pnlCardThisWeek.add(lblThisWeekCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblThisWeekTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblThisWeekTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblThisWeekTitle.setText("THIS WEEK");
        pnlCardThisWeek.add(lblThisWeekTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlTreatmentContent.add(pnlCardThisWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 280, 90));

        pnlCardThisMonth.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardThisMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlCardThisMonth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThisMonthCount.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblThisMonthCount.setForeground(new java.awt.Color(74, 91, 106));
        lblThisMonthCount.setText("0");
        pnlCardThisMonth.add(lblThisMonthCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 190, 36));

        lblThisMonthTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblThisMonthTitle.setForeground(new java.awt.Color(110, 125, 135));
        lblThisMonthTitle.setText("THIS MONTH");
        pnlCardThisMonth.add(lblThisMonthTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, 190, 18));

        pnlTreatmentContent.add(pnlCardThisMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 280, 90));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblTitle.setText("Treatments");
        pnlTreatmentContent.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 35));

        lblSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblSubtitle.setText("Record diagnoses and treatments");
        pnlTreatmentContent.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 20));

        pnlTreatmentDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlTreatmentDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        pnlTreatmentDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormSubtitle.setForeground(new java.awt.Color(110, 125, 135));
        lblFormSubtitle.setText("Record a diagnosis and treatment for a visit");
        pnlTreatmentDetails.add(lblFormSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, 500, 20));

        lblformTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblformTitle.setForeground(new java.awt.Color(74, 91, 106));
        lblformTitle.setText("TREATMENT RECORD");
        pnlTreatmentDetails.add(lblformTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 500, 25));

        lblTreatmentDetails.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTreatmentDetails.setForeground(new java.awt.Color(113, 128, 140));
        lblTreatmentDetails.setText("TREATMENT DETAILS");
        pnlTreatmentDetails.add(lblTreatmentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 366, 18));

        cmbAppointment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlTreatmentDetails.add(cmbAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 32));

        lblStaff.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblStaff.setForeground(new java.awt.Color(113, 128, 140));
        lblStaff.setText("STAFF");
        pnlTreatmentDetails.add(lblStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 270, 18));

        cmbStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlTreatmentDetails.add(cmbStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 270, 32));

        lblDiagnosis.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDiagnosis.setForeground(new java.awt.Color(113, 128, 140));
        lblDiagnosis.setText("DIAGNOSIS");
        pnlTreatmentDetails.add(lblDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 270, 18));

        lblTreatmentDate.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTreatmentDate.setForeground(new java.awt.Color(113, 128, 140));
        lblTreatmentDate.setText("TREATMENT DATE (YYYY-MM-DD)");
        pnlTreatmentDetails.add(lblTreatmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 270, 18));

        lblAppointment.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblAppointment.setForeground(new java.awt.Color(113, 128, 140));
        lblAppointment.setText("APPOINTMENT");
        pnlTreatmentDetails.add(lblAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, 18));

        lblNotes.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblNotes.setForeground(new java.awt.Color(113, 128, 140));
        lblNotes.setText("NOTES");
        pnlTreatmentDetails.add(lblNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 770, 18));

        lblMessage.setForeground(java.awt.Color.red);
        pnlTreatmentDetails.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 600, 20));

        btnAddTreatment.setBackground(new java.awt.Color(157, 201, 163));
        btnAddTreatment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddTreatment.setForeground(new java.awt.Color(74, 91, 106));
        btnAddTreatment.setText("Add Treatment");
        btnAddTreatment.addActionListener(this::btnAddTreatmentActionPerformed);
        pnlTreatmentDetails.add(btnAddTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 355, 270, 45));

        btnUpdateTreatment.setBackground(new java.awt.Color(190, 210, 230));
        btnUpdateTreatment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateTreatment.setForeground(new java.awt.Color(74, 91, 106));
        btnUpdateTreatment.setText("Update Status");
        btnUpdateTreatment.addActionListener(this::btnUpdateTreatmentActionPerformed);
        pnlTreatmentDetails.add(btnUpdateTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 355, 270, 45));

        btnDeleteTreatment.setBackground(new java.awt.Color(220, 170, 170));
        btnDeleteTreatment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteTreatment.setForeground(new java.awt.Color(120, 40, 40));
        btnDeleteTreatment.setText("Delete");
        btnDeleteTreatment.addActionListener(this::btnDeleteTreatmentActionPerformed);
        pnlTreatmentDetails.add(btnDeleteTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 355, 270, 45));

        btnClearTreatment.setBackground(new java.awt.Color(235, 235, 230));
        btnClearTreatment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearTreatment.setForeground(new java.awt.Color(74, 91, 106));
        btnClearTreatment.setText("Clear");
        btnClearTreatment.addActionListener(this::btnClearTreatmentActionPerformed);
        pnlTreatmentDetails.add(btnClearTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 355, 270, 45));

        txtDiagnosis.addActionListener(this::txtDiagnosisActionPerformed);
        pnlTreatmentDetails.add(txtDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 270, 32));

        txtTreatmentDate.addActionListener(this::txtTreatmentDateActionPerformed);
        pnlTreatmentDetails.add(txtTreatmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 270, 32));

        txtTreatmentDetails.setColumns(20);
        txtTreatmentDetails.setRows(5);
        jScrollPane2.setViewportView(txtTreatmentDetails);

        pnlTreatmentDetails.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 1140, 40));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        pnlTreatmentDetails.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 1140, 70));

        pnlTreatmentContent.add(pnlTreatmentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1180, 420));

        lblTreatmentListTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTreatmentListTitle.setForeground(new java.awt.Color(113, 128, 140));
        lblTreatmentListTitle.setText("ALL TREATMENTS");
        pnlTreatmentContent.add(lblTreatmentListTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 400, 25));

        tblTreatments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Appointment", "Pet", "Diagnosis", "Treatment Details", "Date", "Staff", "Notes"
            }
        ));
        jScrollPane1.setViewportView(tblTreatments);

        pnlTreatmentContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 658, 1180, 160));

        getContentPane().add(pnlTreatmentContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTreatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTreatmentActionPerformed

    private void btnUpdateTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTreatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateTreatmentActionPerformed

    private void btnDeleteTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTreatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteTreatmentActionPerformed

    private void btnClearTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTreatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearTreatmentActionPerformed

    private void txtDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosisActionPerformed

    private void txtTreatmentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTreatmentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTreatmentDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TreatmentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTreatment;
    private javax.swing.JButton btnClearTreatment;
    private javax.swing.JButton btnDeleteTreatment;
    private javax.swing.JButton btnUpdateTreatment;
    private javax.swing.JComboBox<String> cmbAppointment;
    private javax.swing.JComboBox<String> cmbStaff;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblAppointment;
    private javax.swing.JLabel lblDiagnosis;
    private javax.swing.JLabel lblFormSubtitle;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblThisMonthCount;
    private javax.swing.JLabel lblThisMonthTitle;
    private javax.swing.JLabel lblThisWeekCount;
    private javax.swing.JLabel lblThisWeekTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTodayCount;
    private javax.swing.JLabel lblTodayTitle;
    private javax.swing.JLabel lblTotalCount;
    private javax.swing.JLabel lblTotalTitle;
    private javax.swing.JLabel lblTreatmentDate;
    private javax.swing.JLabel lblTreatmentDetails;
    private javax.swing.JLabel lblTreatmentListTitle;
    private javax.swing.JLabel lblformTitle;
    private javax.swing.JPanel pnlCardThisMonth;
    private javax.swing.JPanel pnlCardThisWeek;
    private javax.swing.JPanel pnlCardToday;
    private javax.swing.JPanel pnlCardTotal;
    private javax.swing.JPanel pnlTreatmentContent;
    private javax.swing.JPanel pnlTreatmentDetails;
    private view.SidebarPanel sidebarPanel1;
    private javax.swing.JTable tblTreatments;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextField txtTreatmentDate;
    private javax.swing.JTextArea txtTreatmentDetails;
    // End of variables declaration//GEN-END:variables
}
